(()=>{
const account=document.querySelector('#accountModal');if(!account)return;
const email=account.querySelector('input[type="email"]');const child1=document.querySelector('#child1');const child2=document.querySelector('#child2');
const avatars=['🧒🏾','🧑🏻','👧🏽','👦🏼','🧒🏻','👧🏾','👦🏿','🧑🏽'];
let selectedAvatar=localStorage.getItem('jamkar_avatar')||avatars[0];
const top=account.querySelector('.modalHead');top.insertAdjacentHTML('afterend',`<div class="accountTabs"><button class="accountTab active" data-mode="create">Create account</button><button class="accountTab" data-mode="signin">Parent sign in</button></div><div class="accountNotice"><strong>🔐 Parent account protection</strong><small>Children use their own profile names. Parent email, password and payment details are never shown in the child area.</small></div>`);
const grid=account.querySelector('.accountGrid');grid.insertAdjacentHTML('beforeend',`<div class="field full" id="passwordFields"><div class="passwordRow"><div><label>Create password</label><input id="parentPassword" type="password" minlength="8" placeholder="At least 8 characters" autocomplete="new-password"></div><div><label>Confirm password</label><input id="parentPassword2" type="password" minlength="8" placeholder="Repeat password" autocomplete="new-password"></div></div></div><div class="field full"><label>Child avatar</label><div class="avatarPicker" id="avatarPicker">${avatars.map(a=>`<button type="button" class="avatarChoice ${a===selectedAvatar?'active':''}" data-avatar="${a}">${a}</button>`).join('')}</div></div>`);
const save=document.querySelector('#saveProfiles');save.insertAdjacentHTML('beforebegin',`<div class="termsRow" id="termsRow"><input id="parentTerms" type="checkbox"><label for="parentTerms">I confirm I am the parent or guardian creating this family account and I agree to the parent privacy, child-safety and purchase terms.</label></div><div id="accountStatus" class="accountStatus"></div>`);
const pay=document.querySelector('#paySection');pay.insertAdjacentHTML('beforeend',`<div class="secureCheckout"><div style="font-size:28px">🛡️</div><div><b>Secure £4.99 one-time unlock</b><span>Checkout will be completed through Revolut. JamKar will unlock access only after the payment is verified by the server.</span></div></div>`);
let mode='create';function setMode(next){mode=next;document.querySelectorAll('.accountTab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.querySelector('#passwordFields').style.display='block';document.querySelector('#termsRow').style.display=mode==='create'?'flex':'none';document.querySelector('#accountHeading').textContent=mode==='create'?'Create parent account':'Parent sign in';document.querySelector('#parentPassword2').parentElement.style.display=mode==='create'?'block':'none';save.textContent=mode==='create'?'Save family profile':'Sign in (demo)'}document.querySelectorAll('.accountTab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('.avatarChoice').forEach(b=>b.onclick=()=>{selectedAvatar=b.dataset.avatar;document.querySelectorAll('.avatarChoice').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const prior=save.onclick;save.onclick=()=>{const status=document.querySelector('#accountStatus');status.className='accountStatus';status.textContent='';const e=(email.value||'').trim();const pass=document.querySelector('#parentPassword').value;const pass2=document.querySelector('#parentPassword2').value;if(!/^\S+@\S+\.\S+$/.test(e)){status.textContent='Enter a valid parent email address.';return}if(pass.length<8){status.textContent='Password must contain at least 8 characters.';return}if(mode==='create'&&pass!==pass2){status.textContent='The two password entries do not match.';return}if(mode==='create'&&!document.querySelector('#parentTerms').checked){status.textContent='Please confirm the parent/guardian terms to continue.';return}if(prior)prior();if(document.querySelector('#profileError')?.textContent)return;localStorage.setItem('jamkar_parent_email_demo',e);localStorage.setItem('jamkar_avatar',selectedAvatar);document.querySelectorAll('.avatar').forEach(a=>a.textContent=selectedAvatar);status.classList.add('ok');status.textContent=mode==='create'?'Family profile ready on this device. Production authentication will replace this demo storage.':'Demo sign-in complete on this device.';toast(mode==='create'?'Family profile created':'Parent signed in')};
const savedAvatar=localStorage.getItem('jamkar_avatar');if(savedAvatar)document.querySelectorAll('.avatar').forEach(a=>a.textContent=savedAvatar);
})();