(()=>{
const priorStart=startLevel;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function complete(msg='Challenge complete! ✨'){
 const n=state.selectedLevel,key=state.activeProfile+'|'+state.selected.name;
 if(n>=30){state.progress[key]=30;save();renderStats();renderWorlds();renderLevels();els.stage.innerHTML=`<div class="victory"><div class="victoryIcon">🏆</div><h3>${state.selected.name} mastered!</h3><p>${state.activeProfile} completed all 30 levels.</p><button class="primary" id="advancedClose">Choose another world</button></div>`;document.querySelector('#advancedClose').onclick=()=>els.modal.classList.remove('open');return}
 state.progress[key]=Math.max(progressFor(state.selected.name),n+1);save();renderStats();renderWorlds();renderLevels();const f=document.querySelector('#feedback');if(f)f.textContent=msg;setTimeout(()=>startLevel(n+1),650)
}
function sequence(title,icon,items,len){const n=state.selectedLevel,target=Array.from({length:len},()=>items[Math.floor(Math.random()*items.length)]);let i=0;els.stage.innerHTML=`<div class="miniGame advancedGame"><div class="missionCharacter">${icon}</div><div class="eyebrow">${title} · Level ${n}</div><h3>Memory sequence</h3><p class="gameHint">Repeat: <b class="sequenceTarget">${target.join(' → ')}</b></p><div class="commandBank">${items.map(x=>`<button class="commandBtn" data-adv="${x}">${x}</button>`).join('')}</div><p class="note" id="feedback">Step 1 of ${target.length}</p></div>`;document.querySelectorAll('[data-adv]').forEach(b=>b.onclick=()=>{if(b.dataset.adv===target[i]){i++;if(i===target.length)complete('Excellent memory! 🧠');else document.querySelector('#feedback').textContent=`Step ${i+1} of ${target.length}`}else{i=0;document.querySelector('#feedback').textContent='Sequence reset — watch the pattern and try again.'}})}
function sortChallenge(title,icon,leftLabel,rightLabel,items){let remaining=items.length,errors=0;els.stage.innerHTML=`<div class="miniGame advancedGame"><div class="missionCharacter">${icon}</div><div class="eyebrow">${title} · Level ${state.selectedLevel}</div><h3>Sort the mission cards</h3><div class="sortZones"><div><b>${leftLabel}</b></div><div><b>${rightLabel}</b></div></div><div class="sortCards">${shuffle(items).map((x,i)=>`<div class="sortCard" data-card="${i}"><strong>${x[0]}</strong><button data-sort="0" data-i="${i}">← ${leftLabel}</button><button data-sort="1" data-i="${i}">${rightLabel} →</button></div>`).join('')}</div><p class="note" id="feedback">Sort all ${items.length} cards correctly.</p></div>`;document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const idx=Number(b.dataset.i),card=document.querySelector(`[data-card="${idx}"]`);if(Number(b.dataset.sort)===items[idx][1]){card.classList.add('sorted');card.querySelectorAll('button').forEach(x=>x.disabled=true);remaining--;if(!remaining)complete(errors?'Mission complete — you corrected the tricky ones!':'Perfect sorting! ⭐')}else{errors++;card.classList.add('shake');setTimeout(()=>card.classList.remove('shake'),350);document.querySelector('#feedback').textContent='Not quite — try that card again.'}})}
function orderChallenge(title,icon,steps){const target=steps.map((_,i)=>i),order=[];els.stage.innerHTML=`<div class="miniGame advancedGame"><div class="missionCharacter">${icon}</div><div class="eyebrow">${title} · Level ${state.selectedLevel}</div><h3>Build the correct order</h3><div class="orderBank">${shuffle(steps.map((x,i)=>[x,i])).map(([x,i])=>`<button class="orderStep" data-step="${i}">${x}</button>`).join('')}</div><div class="orderTrail" id="orderTrail">Start →</div><p class="note" id="feedback">Choose the first step.</p></div>`;document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const wanted=target[order.length];if(Number(b.dataset.step)===wanted){order.push(wanted);b.disabled=true;b.classList.add('used');document.querySelector('#orderTrail').textContent='Start → '+order.map(i=>steps[i]).join(' → ');if(order.length===steps.length)complete('Great planning! 🛠️');else document.querySelector('#feedback').textContent=`Choose step ${order.length+1}.`}else document.querySelector('#feedback').textContent='That step comes later. Think about what must happen first.'})}
function mathMission(){const n=state.selectedLevel,goal=30+(n%8)*5,values=[2+n%5,3+n%7,5+n%6,8+n%4];let total=0,moves=Math.max(4,8-Math.floor((n-15)/5));els.stage.innerHTML=`<div class="miniGame advancedGame"><div class="missionCharacter">🪐</div><div class="eyebrow">Math Galaxy · Level ${n}</div><h3>Fuel the rover to exactly ${goal}</h3><div class="meter"><i id="mathMeter" style="width:0%"></i></div><div class="commandBank">${values.map(v=>`<button class="commandBtn" data-num="${v}">+${v}</button>`).join('')}</div><p class="note" id="feedback">Fuel: 0/${goal} · ${moves} moves available</p></div>`;document.querySelectorAll('[data-num]').forEach(b=>b.onclick=()=>{if(moves<=0)return;total+=Number(b.dataset.num);moves--;document.querySelector('#mathMeter').style.width=`${Math.min(100,total/goal*100)}%`;if(total===goal)return complete('Exact fuel target reached! 🚀');if(total>goal){total=0;moves=Math.max(4,8-Math.floor((n-15)/5));document.querySelector('#mathMeter').style.width='0%';document.querySelector('#feedback').textContent=`Too much fuel — reset to 0/${goal}. Try a new combination.`;return}document.querySelector('#feedback').textContent=`Fuel: ${total}/${goal} · ${moves} moves left${moves===0?' — reset and try another combination.':''}`;if(moves===0){setTimeout(()=>{total=0;moves=Math.max(4,8-Math.floor((n-15)/5));document.querySelector('#mathMeter').style.width='0%';document.querySelector('#feedback').textContent=`Fuel: 0/${goal} · ${moves} moves available`},700)}})}
function puzzleMission(){const n=state.selectedLevel;sequence('Puzzle Temple','🧩',['🔺','🔵','🟨','⭐'],Math.min(8,4+Math.floor((n-15)/4)))}
function scienceMission(){sortChallenge('Science Lab','🧪','Renewable','Non-renewable',[['Wind',0],['Solar',0],['Coal',1],['Oil',1],['Hydro',0],['Gas',1]])}
function futureMission(){sortChallenge('Future City','🤖','City solution','City problem',[['Protected cycle lanes',0],['Leaking water pipes',1],['Solar roofs',0],['Unsafe crossings',1],['Urban trees',0],['Heavy air pollution',1]])}
function wordMission(){const n=state.selectedLevel;const sets=[['The','brave','explorer','found','the','map.'],['A','bright','comet','crossed','the','sky.'],['Our','robot','carefully','fixed','the','bridge.']];orderChallenge('Word Quest','📚',sets[n%sets.length])}
function explorerMission(){sortChallenge('World Explorer','🗺️','Natural','Human-made',[['River',0],['Mountain',0],['Railway',1],['Bridge',1],['Desert',0],['Airport',1]])}
function engineeringMission(){orderChallenge('Engineering Bay','🛠️',['Plan','Choose materials','Build prototype','Test','Improve'])}
function weatherMission(){orderChallenge('Weather Watch','🌦️',['Observe sky','Measure conditions','Compare data','Make forecast'])}
function languageMission(){orderChallenge('Language Lab','🗣️',['Listen','Think','Speak clearly','Check understanding'])}
function gardenMission(){orderChallenge('Garden Guardians','🌱',['Prepare soil','Plant seed','Water','Give light','Observe growth'])}
function robotMission(){sequence('Robot Factory','⚙️',['⬆️','➡️','⬇️','⬅️'],Math.min(8,4+Math.floor((state.selectedLevel-15)/4)))}
function musicMission(){sequence('Music Makers','🎵',['🥁','🎹','🎸','🎺'],Math.min(8,4+Math.floor((state.selectedLevel-15)/4)))}
startLevel=function(n){state.selectedLevel=n;if(n<15)return priorStart(n);switch(state.selected?.name){case'Math Galaxy':mathMission();break;case'Puzzle Temple':puzzleMission();break;case'Science Lab':scienceMission();break;case'Future City':futureMission();break;case'Word Quest':wordMission();break;case'World Explorer':explorerMission();break;case'Engineering Bay':engineeringMission();break;case'Weather Watch':weatherMission();break;case'Language Lab':languageMission();break;case'Garden Guardians':gardenMission();break;case'Robot Factory':robotMission();break;case'Music Makers':musicMission();break;default:priorStart(n)}};
})();