const worlds=[
{name:'Dino Frontier',emoji:'🦖',cat:'Adventure',cls:'c1',free:true,desc:'Explore prehistoric Earth, fossils, food chains and survival puzzles.'},
{name:'Deep Ocean',emoji:'🐋',cat:'Science',cls:'c2',free:true,desc:'Dive through reefs, trenches and mysterious deep-sea ecosystems.'},
{name:'Ancient Worlds',emoji:'🏺',cat:'History',cls:'c3',free:true,desc:'Build knowledge across Egypt, Nubia, Rome, Greece and early cities.'},
{name:'Wild Planet',emoji:'🦁',cat:'Nature',cls:'c4',free:true,desc:'Habitats, animals, climate and conservation challenges.'},
{name:'Deep Space',emoji:'🚀',cat:'Science',cls:'c5',free:true,desc:'Plan missions, learn planets and travel from Earth to distant stars.'},
{name:'Future City',emoji:'🤖',cat:'Logic',cls:'c6',free:false,desc:'Design a smart city with clean energy, transport and robotics.'},
{name:'Word Quest',emoji:'📚',cat:'English',cls:'c7',free:false,desc:'Vocabulary, spelling, reading and grammar missions.'},
{name:'Math Galaxy',emoji:'➗',cat:'Maths',cls:'c8',free:false,desc:'Numbers, arithmetic, patterns, geometry and problem solving.'},
{name:'Science Lab',emoji:'🧪',cat:'Science',cls:'c4',free:false,desc:'Run safe virtual experiments and discover how things work.'},
{name:'Puzzle Temple',emoji:'🧩',cat:'Puzzles',cls:'c3',free:false,desc:'Pattern, sequence, memory and spatial puzzles.'},
{name:'Eco Rescue',emoji:'🌍',cat:'Nature',cls:'c2',free:false,desc:'Clean oceans, restore forests and protect wildlife.'},
{name:'Code Crew',emoji:'💻',cat:'Logic',cls:'c5',free:false,desc:'Learn sequencing, loops and computational thinking through play.'},
{name:'Time Builder',emoji:'🏗️',cat:'Creative',cls:'c1',free:false,desc:'Build your own civilisation from prehistoric camps to future worlds.'},
{name:'Sky Racers',emoji:'🛸',cat:'Challenge',cls:'c6',free:false,desc:'Fast reaction and strategy missions with child-friendly competition.'},
{name:'Memory Islands',emoji:'🧠',cat:'Puzzles',cls:'c7',free:false,desc:'Train attention and working memory across colourful islands.'},
{name:'World Explorer',emoji:'🗺️',cat:'Geography',cls:'c4',free:false,desc:'Countries, landmarks, maps, climates and cultures.'}
];
const state={paid:false,activeProfile:localStorage.getItem('jamkar_profile')||'Explorer',progress:JSON.parse(localStorage.getItem('jamkar_progress')||'{}'),category:'All',selected:null,selectedLevel:1};
const els={worlds:document.querySelector('#worlds'),search:document.querySelector('#search'),modal:document.querySelector('#worldModal'),account:document.querySelector('#accountModal'),worldTitle:document.querySelector('#worldTitle'),levelGrid:document.querySelector('#levelGrid'),stage:document.querySelector('#gameStage'),profileName:document.querySelector('#profileName'),profileBtn:document.querySelector('#profileBtn'),trialText:document.querySelector('#trialText'),statWorlds:document.querySelector('#statWorlds'),statLevels:document.querySelector('#statLevels')};
function save(){localStorage.setItem('jamkar_progress',JSON.stringify(state.progress));localStorage.setItem('jamkar_profile',state.activeProfile)}
function progressFor(name){return Math.max(1,Number(state.progress[state.activeProfile+'|'+name]||1))}
function completedCount(){return Object.entries(state.progress).filter(([k])=>k.startsWith(state.activeProfile+'|')).reduce((a,[,v])=>a+Math.max(0,Number(v)-1),0)}
function renderStats(){els.statWorlds.textContent=worlds.length;els.statLevels.textContent=completedCount();els.profileName.textContent=state.activeProfile;els.profileBtn.textContent='👤 '+state.activeProfile;els.trialText.textContent=state.paid?'Lifetime access active':'5 worlds free to Level 3'}
function renderWorlds(){let q=(els.search?.value||'').toLowerCase().trim();let list=worlds.filter(w=>(state.category==='All'||w.cat===state.category)&&(!q||[w.name,w.cat,w.desc].join(' ').toLowerCase().includes(q)));els.worlds.innerHTML=list.map(w=>{let p=progressFor(w.name),locked=!state.paid&&!w.free,pct=Math.min(100,(p-1)/30*100);return `<button class="worldCard" data-world="${w.name}"><div class="worldVisual ${w.cls}"><span>${w.emoji}</span></div><div class="worldBody"><div class="worldTop"><h3>${w.name}</h3><span class="badge ${w.free&&!state.paid?'free':''}">${locked?'🔒 Full':state.paid?'Unlocked':'Free'}</span></div><p>${w.desc}</p><div class="progress"><i style="width:${pct}%"></i></div><div class="progressRow"><span>Level ${Math.min(p,30)} / 30</span><span>${w.cat}</span></div></div></button>`}).join('');document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>openWorld(b.dataset.world));}
function openWorld(name){let w=worlds.find(x=>x.name===name);if(!w)return;if(!state.paid&&!w.free){openAccount('unlock');return}state.selected=w;state.selectedLevel=Math.min(30,progressFor(w.name));els.worldTitle.textContent=w.emoji+' '+w.name;renderLevels();els.modal.classList.add('open');document.body.classList.add('game-open');requestAnimationFrame(()=>{startLevel(state.selectedLevel);document.querySelector(`[data-level="${state.selectedLevel}"]`)?.scrollIntoView({behavior:'instant',block:'nearest',inline:'center'})})}
function closeWorld(){els.modal.classList.remove('open');document.body.classList.remove('game-open')}
function renderLevels(){let p=progressFor(state.selected.name);els.levelGrid.innerHTML=Array.from({length:30},(_,i)=>{let n=i+1,trialLock=!state.paid&&n>3,progLock=n>p,locked=trialLock||progLock,done=n<p;return `<button class="level ${done?'done':''} ${n===p?'current':''} ${locked?'locked':''}" data-level="${n}" ${locked?'disabled':''} aria-label="Level ${n}${locked?' locked':''}"><span>${locked?'🔒':n}</span><small>${done?'✓':n===p?'Play':'Level'}</small></button>`}).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{state.selectedLevel=Number(b.dataset.level);startLevel(state.selectedLevel);document.querySelectorAll('.level').forEach(x=>x.classList.toggle('playing',Number(x.dataset.level)===state.selectedLevel))})}
const banks={
'Dino Frontier':[['Which animal lived millions of years ago?',['Dinosaur','Robot','Astronaut','Submarine'],0],['A fossil is usually found in…',['Rock','Clouds','Plastic','Moonlight'],0],['A plant-eating dinosaur is called…',['Herbivore','Carnivore','Pilot','Miner'],0]],
'Deep Ocean':[['Which zone receives the most sunlight?',['Surface zone','Abyss','Trench floor','Core'],0],['Coral reefs are home to…',['Many species','No life','Only sharks','Only plants'],0],['What helps fish breathe?',['Gills','Lungs only','Feathers','Roots'],0]],
'Ancient Worlds':[['The pyramids of Giza are in…',['Egypt','Brazil','Japan','Canada'],0],['Nubia was closely linked to the River…',['Nile','Thames','Amazon','Danube'],0],['Ancient writing on clay tablets is linked with…',['Mesopotamia','Antarctica','Mars','Pacific Ocean'],0]],
'Wild Planet':[['A lion mainly lives in…',['Savannah','Deep ocean','Arctic sea','Space'],0],['Animals need habitats for…',['Food and shelter','Wi-Fi only','Fuel','Coins'],0],['Protecting forests helps…',['Biodiversity','Pollution','Litter','Noise'],0]],
'Deep Space':[['Earth orbits the…',['Sun','Moon','Mars','Polaris'],0],['Which is a planet?',['Saturn','Orion','Milky Way','Sunlight'],0],['Astronauts use spacesuits mainly for…',['Protection and life support','Fashion only','Swimming','Driving'],0]],
'Word Quest':[['Choose the correctly spelt word.',['Adventure','Adventur','Advencher','Advanture'],0],['Which word is a verb?',['Run','Blue','Mountain','Quiet'],0],['Complete: The children ___ playing.',['are','is','be','am'],0]],
'Math Galaxy':[['What is 8 × 6?',['48','42','54','36'],0],['Half of 30 is…',['15','10','20','25'],0],['A triangle has…',['3 sides','4 sides','5 sides','6 sides'],0]],
'Science Lab':[['Water freezes at approximately…',['0°C','50°C','100°C','200°C'],0],['Plants use sunlight for…',['Photosynthesis','Teleportation','Melting','Orbiting'],0],['A magnet strongly attracts…',['Iron','Wood','Glass','Paper'],0]],
'Puzzle Temple':[['What comes next: 2, 4, 6, 8…',['10','9','12','7'],0],['Which is different?',['Triangle','Square','Circle','Banana'],3],['Complete: A, C, E, G…',['I','H','J','K'],0]],
'Eco Rescue':[['Which action reduces waste?',['Reuse items','Throw more away','Leave taps running','Burn plastic'],0],['Renewable energy includes…',['Solar','Coal','Diesel only','Petrol only'],0],['Which helps oceans?',['Less plastic litter','More dumping','Oil spills','Overfishing'],0]],
'Code Crew':[['A sequence is…',['Steps in order','A colour','A coin','A planet'],0],['A loop helps us…',['Repeat actions','Delete electricity','Grow a tree instantly','Change gravity'],0],['A bug in code means…',['An error','An insect always','A prize','A password'],0]],
'World Explorer':[['The UK is in…',['Europe','Africa','Asia','South America'],0],['The Sahara is a…',['Desert','Ocean','City','River'],0],['A map scale helps show…',['Distance','Taste','Sound','Temperature only'],0]]
};
function generatedQuestion(w,n){if(w.name==='Future City')return ['Which choice makes a city more sustainable?',['Public transport','More pollution','Wasting energy','Removing parks'],0];if(w.name==='Time Builder')return ['To grow a settlement safely, build first…',['Shelter and water','A spaceport','A skyscraper','A cinema'],0];if(w.name==='Sky Racers')return ['You see a hazard ahead. Best action?',['Slow and plan','Speed up','Close your eyes','Ignore it'],0];if(w.name==='Memory Islands')return ['Remember: ⭐ 🌊 🐚. Which was second?',['🌊','⭐','🐚','🚀'],0];return ['Which answer best shows careful thinking?',['Check clues and choose','Guess without reading','Skip every clue','Always pick last'],0]}
function startLevel(n){state.selectedLevel=n;document.querySelectorAll('.level').forEach(x=>x.classList.toggle('playing',Number(x.dataset.level)===n));let bank=banks[state.selected.name]||[],item=bank[(n-1)%Math.max(bank.length,1)]||generatedQuestion(state.selected,n);let [q,answers,correct]=item;els.stage.innerHTML=`<div class="gameMission"><div class="missionTop"><span class="eyebrow">${state.selected.cat}</span><strong>Level ${n}</strong></div><div class="missionHero">${state.selected.emoji}</div><p class="question">${q}</p><div class="choices">${answers.map((a,i)=>`<button class="choice" data-answer="${i}">${a}</button>`).join('')}</div><p class="note" id="feedback">Choose the best answer.</p></div>`;document.querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>answer(btn,Number(btn.dataset.answer),correct))}
function answer(btn,pick,correct){document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);let fb=document.querySelector('#feedback');if(pick===correct){btn.classList.add('correct');fb.textContent='Excellent! Level complete. ✨';let key=state.activeProfile+'|'+state.selected.name;state.progress[key]=Math.max(progressFor(state.selected.name),state.selectedLevel+1);save();renderStats();setTimeout(()=>{if(!state.paid&&state.selectedLevel===3){closeWorld();openAccount('unlock')}else{renderLevels();renderWorlds();state.selectedLevel=Math.min(30,state.selectedLevel+1);startLevel(state.selectedLevel);document.querySelector(`[data-level="${state.selectedLevel}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}},700)}else{btn.classList.add('wrong');document.querySelector(`[data-answer="${correct}"]`)?.classList.add('correct');fb.textContent='Good try. Look at the highlighted answer and try again.';setTimeout(()=>{document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=false);btn.classList.remove('wrong');document.querySelector(`[data-answer="${correct}"]`)?.classList.remove('correct')},900)}}
function openAccount(mode='join'){els.account.classList.add('open');document.querySelector('#accountHeading').textContent=mode==='unlock'?'Unlock all JamKar worlds':'Parent account & child profiles';document.querySelector('#paySection').style.display=state.paid?'none':'block'}
function toast(msg){let t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.cat;renderWorlds()});
els.search?.addEventListener('input',renderWorlds);document.querySelector('#profileBtn').onclick=()=>openAccount();document.querySelector('#joinHero').onclick=()=>openAccount();document.querySelector('#closeWorld').onclick=closeWorld;document.querySelector('#closeAccount').onclick=()=>els.account.classList.remove('open');
document.querySelector('#saveProfiles').onclick=()=>{let p1=document.querySelector('#child1').value.trim()||'Explorer',p2=document.querySelector('#child2').value.trim(),profiles=[p1,p2].filter(Boolean);localStorage.setItem('jamkar_profiles',JSON.stringify(profiles));state.activeProfile=p1;save();renderStats();renderWorlds();toast('Child profiles saved on this device.')};
document.querySelector('#switchProfile').onchange=e=>{if(!e.target.value)return;state.activeProfile=e.target.value;save();renderStats();renderWorlds();toast('Switched to '+state.activeProfile)};
function loadProfiles(){let ps=JSON.parse(localStorage.getItem('jamkar_profiles')||'["Explorer"]'),s=document.querySelector('#switchProfile');s.innerHTML='<option value="">Switch child profile…</option>'+ps.map(p=>`<option>${p}</option>`).join('');document.querySelector('#child1').value=ps[0]||'';document.querySelector('#child2').value=ps[1]||''}
const checkout=document.querySelector('#demoUnlock');if(checkout){checkout.textContent='Secure checkout loading…';checkout.disabled=true;checkout.onclick=()=>{toast('Please wait for secure account checkout to load.')}}const reset=document.querySelector('#resetDemo');if(reset)reset.style.display='none';
renderStats();loadProfiles();renderWorlds();