const worlds=[
{name:'Dino Frontier',emoji:'🦖',cat:'Adventure',cls:'c1',free:true,desc:'Explore prehistoric Earth, fossils, food chains and survival puzzles.'},{name:'Deep Ocean',emoji:'🐋',cat:'Science',cls:'c2',free:true,desc:'Dive through reefs, trenches and mysterious deep-sea ecosystems.'},{name:'Ancient Worlds',emoji:'🏺',cat:'History',cls:'c3',free:true,desc:'Explore Egypt, Nubia, Rome, Greece and early cities.'},{name:'Wild Planet',emoji:'🦁',cat:'Nature',cls:'c4',free:true,desc:'Habitats, animals, climate and conservation challenges.'},{name:'Deep Space',emoji:'🚀',cat:'Science',cls:'c5',free:true,desc:'Plan missions, learn planets and travel beyond Earth.'},
{name:'Future City',emoji:'🤖',cat:'Logic',cls:'c6',free:false,desc:'Design a smart city with clean energy, transport and robotics.'},{name:'Word Quest',emoji:'📚',cat:'English',cls:'c7',free:false,desc:'Vocabulary, spelling, reading and grammar missions.'},{name:'Math Galaxy',emoji:'➗',cat:'Maths',cls:'c8',free:false,desc:'Numbers, patterns, geometry and problem solving.'},{name:'Science Lab',emoji:'🧪',cat:'Science',cls:'c4',free:false,desc:'Run safe virtual experiments and discover how things work.'},{name:'Puzzle Temple',emoji:'🧩',cat:'Puzzles',cls:'c3',free:false,desc:'Pattern, sequence, memory and spatial puzzles.'},{name:'Eco Rescue',emoji:'🌍',cat:'Nature',cls:'c2',free:false,desc:'Clean oceans, restore forests and protect wildlife.'},{name:'Code Crew',emoji:'💻',cat:'Logic',cls:'c5',free:false,desc:'Learn sequencing, loops and computational thinking through play.'},{name:'Time Builder',emoji:'🏗️',cat:'Creative',cls:'c1',free:false,desc:'Build a civilisation from prehistoric camp to future colony.'},{name:'Sky Racers',emoji:'🛸',cat:'Challenge',cls:'c6',free:false,desc:'Fast reaction and strategy missions with child-friendly competition.'},{name:'Memory Islands',emoji:'🧠',cat:'Puzzles',cls:'c7',free:false,desc:'Train attention and memory across colourful islands.'},{name:'World Explorer',emoji:'🗺️',cat:'Geography',cls:'c4',free:false,desc:'Countries, landmarks, maps, climates and cultures.'},
{name:'Music Makers',emoji:'🎵',cat:'Creative',cls:'c6',free:false,desc:'Rhythm, instruments, musical memory and composition.'},{name:'Art Studio',emoji:'🎨',cat:'Creative',cls:'c8',free:false,desc:'Colour, shape, design and visual creativity missions.'},{name:'Weather Watch',emoji:'🌦️',cat:'Science',cls:'c2',free:false,desc:'Clouds, seasons, forecasts and climate observation.'},{name:'Engineering Bay',emoji:'🛠️',cat:'Logic',cls:'c8',free:false,desc:'Build bridges, choose materials and solve engineering puzzles.'},{name:'Language Lab',emoji:'🗣️',cat:'English',cls:'c6',free:false,desc:'Words, meanings, sentence building and communication.'},{name:'Mystery Maze',emoji:'🕵️',cat:'Puzzles',cls:'c3',free:false,desc:'Clues, deduction, codes and safe mystery-solving adventures.'},{name:'Garden Guardians',emoji:'🌱',cat:'Nature',cls:'c4',free:false,desc:'Grow habitats, learn plant life cycles and protect pollinators.'},{name:'Robot Factory',emoji:'⚙️',cat:'Logic',cls:'c5',free:false,desc:'Assemble friendly robots using sequences, parts and logic.'}
];
const state={paid:false,activeProfile:localStorage.getItem('jamkar_profile')||'Explorer',progress:JSON.parse(localStorage.getItem('jamkar_progress')||'{}'),category:'All',selected:null,selectedLevel:1};
try{localStorage.removeItem('jamkar_paid')}catch{}
const els={worlds:document.querySelector('#worlds'),search:document.querySelector('#search'),modal:document.querySelector('#worldModal'),account:document.querySelector('#accountModal'),worldTitle:document.querySelector('#worldTitle'),levelGrid:document.querySelector('#levelGrid'),stage:document.querySelector('#gameStage'),profileName:document.querySelector('#profileName'),profileBtn:document.querySelector('#profileBtn'),trialText:document.querySelector('#trialText'),statWorlds:document.querySelector('#statWorlds'),statLevels:document.querySelector('#statLevels'),hero:document.querySelector('#hero')};
function save(){localStorage.setItem('jamkar_progress',JSON.stringify(state.progress));localStorage.setItem('jamkar_profile',state.activeProfile)}
function progressFor(name){return Math.max(1,Number(state.progress[state.activeProfile+'|'+name]||1))}
function completedCount(){return Object.entries(state.progress).filter(([k])=>k.startsWith(state.activeProfile+'|')).reduce((a,[,v])=>a+Math.max(0,Math.min(30,Number(v))-1),0)}
function renderStats(){els.statWorlds.textContent=worlds.length;els.statLevels.textContent=completedCount();els.profileName.textContent=state.activeProfile;els.profileBtn.textContent='👤 '+state.activeProfile;els.trialText.textContent=state.paid?'Lifetime access active':'5 worlds free to Level 3'}
function renderWorlds(){const q=(els.search?.value||'').toLowerCase().trim(),list=worlds.filter(w=>(state.category==='All'||w.cat===state.category)&&(!q||`${w.name} ${w.cat} ${w.desc}`.toLowerCase().includes(q)));els.worlds.innerHTML=list.map(w=>{const p=progressFor(w.name),locked=!state.paid&&!w.free,pct=Math.min(100,(p-1)/30*100);return `<button class="worldCard" data-world="${w.name}"><div class="worldVisual ${w.cls}"><span>${w.emoji}</span></div><div class="worldBody"><div class="worldTop"><h3>${w.name}</h3><span class="badge ${w.free&&!state.paid?'free':''}">${locked?'🔒 Full':state.paid?'Unlocked':'Free'}</span></div><p>${w.desc}</p><div class="progress"><i style="width:${pct}%"></i></div><div class="progressRow"><span>Level ${Math.min(p,30)} / 30</span><span>${w.cat}</span></div></div></button>`}).join('');document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>openWorld(b.dataset.world))}
function renderLevels(){if(!state.selected)return;const p=progressFor(state.selected.name);els.levelGrid.innerHTML=Array.from({length:30},(_,i)=>{const n=i+1,locked=(!state.paid&&n>3)||n>p,done=n<p;return `<button class="level ${done?'done':''} ${n===p?'current':''} ${locked?'locked':''}" data-level="${n}" ${locked?'disabled':''} aria-label="Level ${n}${locked?' locked':''}"><span>${locked?'🔒':n}</span><small>${done?'✓':n===p?'Play':'Level'}</small></button>`}).join('');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)))}
function openWorld(name){const w=worlds.find(x=>x.name===name);if(!w)return;if(!state.paid&&!w.free){openAccount('unlock');return}state.selected=w;state.selectedLevel=Math.min(30,progressFor(w.name));els.worldTitle.textContent=`${w.emoji} ${w.name}`;renderLevels();els.modal.classList.add('open');document.body.classList.add('game-open');history.pushState({world:w.name},'',`#world=${encodeURIComponent(w.name)}`);requestAnimationFrame(()=>startLevel(state.selectedLevel))}
function closeWorld(push=true){destroyEngine();els.modal.classList.remove('open');document.body.classList.remove('game-open');state.selected=null;if(push&&location.hash.startsWith('#world='))history.pushState({},'',location.pathname+location.search)}
window.addEventListener('popstate',()=>{if(els.modal.classList.contains('open'))closeWorld(false)});
document.querySelector('#backWorld').onclick=()=>closeWorld();document.querySelector('#closeWorld').onclick=()=>closeWorld();

const themes={
'Dino Frontier':{sky:['#c8f5ff','#f4e48d'],ground:'#78b85e',accent:'#4a8f3f',collect:'🦴',goal:'⛺',npcs:['🦕','🦖','🦤'],props:['🌴','🌿','🪨']},'Deep Ocean':{sky:['#8fe9ff','#1977ac'],ground:'#0c5e86',accent:'#22b7c9',collect:'🐚',goal:'⚓',npcs:['🐠','🐢','🐬'],props:['🪸','🌿','🪨']},'Ancient Worlds':{sky:['#ffe7a7','#f0bd6d'],ground:'#c79a52',accent:'#906837',collect:'🏺',goal:'🏛️',npcs:['🐪','🦅','🐈'],props:['🌴','🗿','🧱']},'Wild Planet':{sky:['#d7f7bc','#76c77c'],ground:'#4e9c59',accent:'#2d773f',collect:'🔎',goal:'🏕️',npcs:['🦁','🦓','🐘'],props:['🌳','🌾','🪨']},'Deep Space':{sky:['#6258b8','#11142c'],ground:'#27294a',accent:'#7c6be8',collect:'⭐',goal:'🚀',npcs:['🛸','🤖','🛰️'],props:['🌌','☄️','🪨']},'Music Makers':{sky:['#ffd7ef','#b39be9'],ground:'#9864a5',accent:'#d463a7',collect:'🎵',goal:'🎤',npcs:['🥁','🎺','🎹'],props:['🎶','🎧','🎤']}}
function fallbackTheme(w){const sets=[['#ccecff','#6ea7e9','#5578a6','#5b8dd4'],['#ffe2bd','#f0a97a','#b76f5e','#d98865'],['#d8ffd0','#79c781','#4f9659','#5fac6b'],['#eadbff','#8b78cf','#6256a7','#7968c1']][worlds.indexOf(w)%4];return{sky:[sets[0],sets[1]],ground:sets[2],accent:sets[3],collect:w.emoji,goal:'🏆',npcs:['✨','⭐','💫'],props:[w.emoji,'🔷','🌟']}}
function currentTheme(){return themes[state.selected?.name]||fallbackTheme(state.selected)}
let engine=null,keys=new Set();
function destroyEngine(){if(!engine)return;cancelAnimationFrame(engine.raf);engine=null;els.stage.innerHTML=''}
function startLevel(n){if(!state.selected)return;state.selectedLevel=n;document.querySelectorAll('.level').forEach(x=>x.classList.toggle('playing',Number(x.dataset.level)===n));destroyEngine();buildEngine()}
function buildEngine(){const th=currentTheme(),root=document.createElement('div');root.className='jkGameWorld';root.innerHTML=`<canvas class="jkGameCanvas" aria-label="Playable ${state.selected.name} world"></canvas><div class="jkGameHud"><span class="jkHudPill jkObjective"></span><button class="jkHudPill jkMissionToggle" type="button">🎯 Mission</button></div><div class="jkQuest"></div><div class="jkMovePad" aria-label="Movement controls"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><div class="gameToast"></div>`;els.stage.appendChild(root);const canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d');engine={root,canvas,ctx,x:420,y:740,target:null,t:0,collected:new Set(),collects:[],npcs:[],particles:[],missionDone:false,raf:0,dpr:1};const seed=[...state.selected.name].reduce((a,c)=>a+c.charCodeAt(0),0)+state.selectedLevel*71;for(let i=0;i<5;i++)engine.collects.push({x:250+((seed*(i+3)*17)%1450),y:300+((seed*(i+7)*23)%600),phase:i});for(let i=0;i<9;i++)engine.npcs.push({x:160+((seed*(i+5)*31)%1700),y:260+((seed*(i+9)*37)%760),phase:i*1.2,symbol:th.npcs[i%th.npcs.length]});root.querySelector('.jkObjective').textContent=`Collect 5 ${th.collect} • Level ${state.selectedLevel}`;root.querySelector('.jkMissionToggle').onclick=()=>root.querySelector('.jkQuest').classList.toggle('is-hidden');root.querySelectorAll('[data-dir]').forEach(b=>{let timer;const go=()=>move(b.dataset.dir,18);b.onpointerdown=e=>{e.preventDefault();go();timer=setInterval(go,60)};b.onpointerup=b.onpointerleave=()=>clearInterval(timer)});canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect(),c=camera();engine.target={x:e.clientX-r.left+c.x,y:e.clientY-r.top+c.y}};renderMission();resizeEngine();drawLoop()}
function resizeEngine(){if(!engine)return;const r=engine.root.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);engine.dpr=d;engine.canvas.width=Math.max(1,r.width*d);engine.canvas.height=Math.max(1,r.height*d)}
function camera(){const w=engine.canvas.width/engine.dpr,h=engine.canvas.height/engine.dpr;return{x:Math.max(0,Math.min(2000-w,engine.x-w/2)),y:Math.max(0,Math.min(1200-h,engine.y-h/2)),w,h}}
function move(dir,n=14){if(!engine)return;if(dir==='left')engine.x-=n;if(dir==='right')engine.x+=n;if(dir==='up')engine.y-=n;if(dir==='down')engine.y+=n;engine.x=Math.max(50,Math.min(1950,engine.x));engine.y=Math.max(90,Math.min(1140,engine.y));engine.target=null;checkCollect()}
function gameToast(msg){const t=engine?.root.querySelector('.gameToast');if(!t)return;t.textContent=msg;t.classList.remove('show');void t.offsetWidth;t.classList.add('show')}
function checkCollect(){const th=currentTheme();engine.collects.forEach((c,i)=>{if(engine.collected.has(i))return;if(Math.hypot(engine.x-c.x,engine.y-c.y)<72){engine.collected.add(i);gameToast(`${th.collect} found! ${engine.collected.size}/5`);engine.root.querySelector('.jkObjective').textContent=engine.collected.size<5?`Collect 5 ${th.collect} • ${engine.collected.size}/5`:'Collection complete — finish the mission!';if(engine.collected.size===5)renderMission(true)}})}
function drawAvatar(ctx,x,y,t){ctx.save();ctx.translate(x,y+Math.sin(t*7)*3);ctx.fillStyle='rgba(16,45,70,.18)';ctx.beginPath();ctx.ellipse(0,32,26,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#25b982';ctx.beginPath();ctx.roundRect(-18,-1,36,42,13);ctx.fill();ctx.fillStyle='#f2b184';ctx.beginPath();ctx.arc(0,-16,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#252c3e';ctx.beginPath();ctx.arc(0,-20,17,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#1b2d42';ctx.beginPath();ctx.arc(-5,-16,2,0,Math.PI*2);ctx.arc(5,-16,2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawLoop(){if(!engine?.root.isConnected)return;const e=engine,ctx=e.ctx,t=performance.now()/1000,c=camera(),d=e.dpr,th=currentTheme();if(e.target){const dx=e.target.x-e.x,dy=e.target.y-e.y,dist=Math.hypot(dx,dy);if(dist>7){e.x+=dx/dist*3.5;e.y+=dy/dist*3.5;checkCollect()}else e.target=null}ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,c.w,c.h);const g=ctx.createLinearGradient(0,0,0,c.h);g.addColorStop(0,th.sky[0]);g.addColorStop(1,th.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,c.w,c.h);ctx.save();ctx.translate(-c.x,-c.y);ctx.fillStyle=th.ground;ctx.fillRect(0,610,2000,590);for(let i=0;i<28;i++){const x=(i*149)%2000,y=640+((i*103)%500);ctx.fillStyle=hexAlpha(th.accent,.18);ctx.beginPath();ctx.arc(x,y,28+(i%5)*10,0,Math.PI*2);ctx.fill()}ctx.font='54px system-ui';ctx.textAlign='center';th.props.forEach((p,j)=>{for(let i=0;i<5;i++)ctx.fillText(p,120+j*520+i*110,520+((i+j)%3)*145)});e.npcs.forEach(n=>ctx.fillText(n.symbol,n.x+Math.sin(t*.8+n.phase)*38,n.y+Math.cos(t+n.phase)*12));e.collects.forEach((o,i)=>{if(e.collected.has(i))return;ctx.beginPath();ctx.fillStyle='rgba(255,255,255,.78)';ctx.arc(o.x,o.y+Math.sin(t*2+o.phase)*8,34,0,Math.PI*2);ctx.fill();ctx.fillText(th.collect,o.x,o.y+8+Math.sin(t*2+o.phase)*8)});ctx.font='72px system-ui';ctx.fillText(th.goal,1780,245);drawAvatar(ctx,e.x,e.y,t);ctx.restore();e.raf=requestAnimationFrame(drawLoop)}
function hexAlpha(hex,a){if(!/^#([0-9a-f]{6})$/i.test(hex))return `rgba(50,100,150,${a})`;const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${(n>>8)&255},${n&255},${a})`}

const missionBanks={
'Dino Frontier':[['A fossil is partly exposed. What should you do first?','Brush carefully around it',['Pull it quickly','Pour water on it','Step on the rock']],['Which dinosaur diet means plant-eater?','Herbivore',['Carnivore','Omnivore only','Predator']],['Why record the rock layer around a fossil?','It helps date and understand the find',['It changes the fossil colour','It makes it heavier','It is only decoration']]],
'Deep Ocean':[['A reef has plastic nearby. Best action?','Remove litter carefully',['Break coral','Feed wild fish','Move coral by hand']],['Fish use which organ to breathe underwater?','Gills',['Feathers','Roots','Fins only']],['Why should divers avoid touching coral?','Coral is fragile and can be damaged',['Coral is metal','It makes the sea warmer','It always swims away']]],
'Ancient Worlds':[['You find writing on an ancient wall. Best action?','Observe and record it',['Scratch a copy','Remove a piece','Paint over it']],['The Nile was important because it provided…','Water and fertile land',['Snow all year','Electricity','Volcanoes']],['Which clue can reveal ancient trade?','Coins and pottery',['Modern plastic','Phone signals','Street lights']]],
'Wild Planet':[['Animals gather at a waterhole. Best observation?','Watch quietly from a safe distance',['Chase them closer','Block the water','Touch the animals']],['Which sign suggests a healthy habitat?','Different species living together',['No plants','Only litter','No water']],['Why are pollinators important?','They help many plants reproduce',['They make rocks','They remove sunlight','They stop all rain']]],
'Deep Space':[['Before crossing a moon ridge, check…','Oxygen and route',['Only speed','Nothing','Music volume']],['Which energy source works well in sunlight?','Solar power',['Coal','Petrol','Wood fire']],['Earth travels around the…','Sun',['Moon','Mars','Polaris']]],
'Music Makers':[['Which instrument belongs to percussion?','Drum',['Flute','Violin','Trumpet']],['A repeating beat pattern is called…','Rhythm',['Orbit','Habitat','Fossil']],['Which word means gradually getting louder?','Crescendo',['Silence','Pause','Echo only']]],
'Math Galaxy':[['What is 8 × 6?','48',['42','54','36']],['Half of 30 is…','15',['10','20','25']],['A triangle has…','3 sides',['4 sides','5 sides','6 sides']]],
'Word Quest':[['Choose the correctly spelt word.','Adventure',['Adventur','Advanture','Advencher']],['Which word is a verb?','Build',['Blue','Tower','Careful']],['Complete: The children ___ playing.','are',['is','be','am']]],
'Science Lab':[['Water freezes at approximately…','0°C',['50°C','100°C','200°C']],['Plants use sunlight for…','Photosynthesis',['Teleportation','Melting','Orbiting']],['A magnet strongly attracts…','Iron',['Wood','Glass','Paper']]]};
function missionFor(){const w=state.selected.name,n=state.selectedLevel,bank=missionBanks[w];if(bank)return bank[(n-1)%bank.length];const generics={Nature:['Which choice best protects nature?','Reduce waste and protect habitats',['Leave litter','Waste water','Disturb wildlife']],Logic:['What is the best way to solve a challenge?','Break it into clear steps',['Guess randomly','Ignore clues','Skip every step']],Puzzles:['What helps with a puzzle?','Look for patterns and clues',['Never check clues','Always choose last','Ignore the rules']],Creative:['What helps a creative project improve?','Try, test and revise',['Never change it','Avoid planning','Copy everything']],English:['Which is the clearest communication?','Use kind, complete sentences',['Use random words','Shout one word','Ignore meaning']],Science:['Good science starts with…','Observation and evidence',['Guessing only','No testing','Ignoring results']]};return generics[state.selected.cat]||['What is the best next step?','Read the clues and choose carefully',['Guess instantly','Ignore the task','Choose randomly']]}
function renderMission(force=false){if(!engine)return;const box=engine.root.querySelector('.jkQuest'),[q,correct,wrong]=missionFor(),answers=[correct,...wrong].sort(()=>Math.random()-.5);box.innerHTML=`<div class="missionPanel"><span class="eyebrow">${state.selected.cat} mission</span><h3>Level ${state.selectedLevel}</h3><p>${q}</p><div class="missionChoices">${answers.map(a=>`<button data-mission="${a===correct?'1':'0'}">${a}</button>`).join('')}</div><p class="note">${engine.collected.size<5?'You can explore first, then return to this mission.':'All collectibles found — finish the mission to clear the level.'}</p></div>`;box.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{if(b.dataset.mission==='1'){b.style.background='#dff9e9';engine.missionDone=true;gameToast('Mission complete! ✨');completeLevel()}else{b.style.background='#fff0f1';gameToast('Try another answer')}});if(force)box.classList.remove('is-hidden')}
function completeLevel(){const key=state.activeProfile+'|'+state.selected.name,n=state.selectedLevel;state.progress[key]=Math.max(progressFor(state.selected.name),Math.min(30,n+1));save();renderStats();renderWorlds();setTimeout(()=>{if(!state.paid&&n===3){closeWorld();openAccount('unlock');return}renderLevels();state.selectedLevel=Math.min(30,n+1);startLevel(state.selectedLevel)},700)}
addEventListener('keydown',e=>{if(!engine||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k==='arrowup'||k==='w'){e.preventDefault();move('up')}if(k==='arrowdown'||k==='s'){e.preventDefault();move('down')}if(k==='arrowleft'||k==='a'){e.preventDefault();move('left')}if(k==='arrowright'||k==='d'){e.preventDefault();move('right')}});addEventListener('resize',resizeEngine);

function openAccount(mode='join'){els.account.classList.add('open');document.querySelector('#accountHeading').textContent=mode==='unlock'?'Unlock all JamKar worlds':'Parent account & child profiles';document.querySelector('#paySection').style.display=state.paid?'none':'block'}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function loadProfiles(){let ps;try{ps=JSON.parse(localStorage.getItem('jamkar_profiles')||'["Explorer"]')}catch{ps=['Explorer']}const s=document.querySelector('#switchProfile');s.innerHTML='<option value="">Switch child profile…</option>'+ps.map(p=>`<option>${p}</option>`).join('');document.querySelector('#child1').value=ps[0]||'';document.querySelector('#child2').value=ps[1]||''}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.cat;renderWorlds()});els.search?.addEventListener('input',renderWorlds);els.profileBtn.onclick=()=>openAccount();document.querySelector('#joinHero').onclick=()=>document.querySelector('#libraryHead').scrollIntoView({behavior:'smooth'});document.querySelector('#parentHero').onclick=()=>openAccount();document.querySelector('#closeAccount').onclick=()=>els.account.classList.remove('open');
document.querySelector('#saveProfiles').onclick=()=>{const p1=document.querySelector('#child1').value.trim()||'Explorer',p2=document.querySelector('#child2').value.trim(),profiles=[p1,p2].filter(Boolean);localStorage.setItem('jamkar_profiles',JSON.stringify(profiles));state.activeProfile=p1;save();renderStats();renderWorlds();toast('Child profiles saved on this device.')};document.querySelector('#switchProfile').onchange=e=>{if(!e.target.value)return;state.activeProfile=e.target.value;save();renderStats();renderWorlds();toast('Switched to '+state.activeProfile)};
function showView(view){if(view==='home'){els.hero.style.display='grid';scrollTo({top:0,behavior:'smooth'})}else if(view==='games'){els.hero.style.display='none';document.querySelector('#libraryHead').scrollIntoView({behavior:'smooth'})}else if(view==='parent')openAccount();else if(view==='achievements')window.JamKarDashboard?.open?.();else if(view==='create'||view==='worlds'){state.category='Creative';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Creative'));renderWorlds();els.hero.style.display='none';document.querySelector('#libraryHead').scrollIntoView({behavior:'smooth'})}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-dock]').forEach(b=>b.onclick=()=>showView(b.dataset.dock));
let audioCtx=null,musicTimer=null,musicOn=false;function tone(freq,dur=.16){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}function toggleMusic(){const btn=document.querySelector('#musicToggle');musicOn=!musicOn;if(musicOn){audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const notes=[523,659,784,659,587,698,880,698],play=()=>{let i=0;musicTimer=setInterval(()=>tone(notes[i++%notes.length],.18),340)};play();btn.textContent='♫ Music on'}else{clearInterval(musicTimer);btn.textContent='♪ Music'}}document.querySelector('#musicToggle').onclick=toggleMusic;
const checkout=document.querySelector('#demoUnlock');if(checkout){checkout.textContent='Sign in to unlock securely with Revolut — £4.99';checkout.disabled=false}document.querySelector('#resetDemo').style.display='none';renderStats();loadProfiles();renderWorlds();