(()=>{
const stage=()=>document.querySelector('#gameStage');
const icon=()=>state?.selected?.emoji||'✨';
function ensureLayers(){const s=stage();if(!s||!state?.selected)return;let hud=s.querySelector('.worldHud');if(!hud){hud=document.createElement('div');hud.className='worldHud';s.appendChild(hud)}hud.innerHTML=`<span>${icon()} ${state.selected.name}</span><span>Level ${state.selectedLevel||1}</span>`;let fx=s.querySelector('.fxLayer');if(!fx){fx=document.createElement('div');fx.className='fxLayer';fx.setAttribute('aria-hidden','true');s.appendChild(fx)}}
function burst(symbols=['✨','⭐','💫'],count=12,x=.5,y=.55){const s=stage();if(!s)return;ensureLayers();const fx=s.querySelector('.fxLayer'),r=s.getBoundingClientRect();for(let i=0;i<count;i++){const p=document.createElement('span');p.className='fxParticle';p.textContent=symbols[i%symbols.length];p.style.left=`${Math.max(0,Math.min(r.width-30,r.width*x+(Math.random()-.5)*80))}px`;p.style.top=`${Math.max(0,Math.min(r.height-30,r.height*y+(Math.random()-.5)*60))}px`;p.style.setProperty('--x',`${(Math.random()-.5)*260}px`);p.style.setProperty('--y',`${-60-Math.random()*220}px`);p.style.setProperty('--r',`${(Math.random()-.5)*240}deg`);p.style.setProperty('--dur',`${650+Math.random()*650}ms`);fx.appendChild(p);setTimeout(()=>p.remove(),1500)}}
function react(type,target){const s=stage();if(!s)return;ensureLayers();s.classList.remove('jk-success','jk-error');void s.offsetWidth;if(type==='success'){s.classList.add('jk-success');burst([icon(),'⭐','✨','🏆'],16,target?((target.getBoundingClientRect().left-s.getBoundingClientRect().left)/s.clientWidth):.5,.55)}else{s.classList.add('jk-error');burst(['💭','↻'],5,.5,.5)}setTimeout(()=>s.classList.remove('jk-success','jk-error'),700)}
function hoverTone(el){if(!window.JamKarAudioPulse)return;window.JamKarAudioPulse(el?.classList.contains('level')?'tick':'hover')}
document.addEventListener('pointerover',e=>{const b=e.target.closest('#worldModal button:not([disabled])');if(b&&e.pointerType!=='touch')hoverTone(b)});
document.addEventListener('click',e=>{const good=e.target.closest('.correct,.hit,.visited,.matched,.used,.filled');const bad=e.target.closest('.wrong,.miss,.bad');if(good)react('success',good);else if(bad)react('error',bad)});
const s=stage();if(s)new MutationObserver(()=>requestAnimationFrame(ensureLayers)).observe(s,{childList:true,subtree:false});window.addEventListener('jamkar:3dmission',()=>react('success'));ensureLayers();
})();