(()=>{
const cfg=window.JAMKAR_CONFIG||{};
const state={mode:'demo',client:null,user:null};
const required=['supabaseUrl','supabaseKey'];
function ready(){return required.every(k=>typeof cfg[k]==='string'&&cfg[k].trim())&&window.supabase?.createClient}
function emit(name,detail={}){window.dispatchEvent(new CustomEvent('jamkar:'+name,{detail}))}
async function refreshUser(){if(!state.client){state.user=null;return null}const {data,error}=await state.client.auth.getUser();if(error&&error.name!=='AuthSessionMissingError')throw error;state.user=data?.user||null;return state.user}
async function init(){if(!ready()){emit('backend',{mode:'demo'});return state}state.client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await refreshUser();state.mode='supabase';state.client.auth.onAuthStateChange((event,session)=>{state.user=session?.user||null;emit('auth',{user:state.user,event})});emit('backend',{mode:'supabase',user:state.user});return state}
async function signUp(email,password){if(!state.client)throw new Error('Backend is not configured yet.');return state.client.auth.signUp({email,password,options:{emailRedirectTo:location.origin}})}
async function signIn(email,password){if(!state.client)throw new Error('Backend is not configured yet.');return state.client.auth.signInWithPassword({email,password})}
async function signOut(){if(!state.client)return;await state.client.auth.signOut();state.user=null;emit('auth',{user:null,event:'SIGNED_OUT'})}
async function resetPassword(email){if(!state.client)throw new Error('Backend is not configured yet.');return state.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin})}
async function updatePassword(password){if(!state.client||!state.user)throw new Error('Open the password reset link from your email first.');return state.client.auth.updateUser({password})}
async function getFamily(){if(!state.client||!state.user)return null;const [{data:account,error:ae},{data:children,error:ce}]=await Promise.all([state.client.from('parent_accounts').select('user_id,lifetime_unlocked,last_active_slot,created_at').eq('user_id',state.user.id).maybeSingle(),state.client.from('child_profiles').select('id,slot,username,avatar_key,created_at').order('slot')]);if(ae)throw ae;if(ce)throw ce;return{account,children:children||[]}}
async function setActiveChildSlot(slot){if(!state.client||!state.user)return;const clean=Number(slot);if(![1,2].includes(clean))return;const {error}=await state.client.from('parent_accounts').update({last_active_slot:clean}).eq('user_id',state.user.id);if(error)throw error}
async function saveChild(slot,username,avatarKey='explorer'){if(!state.client||!state.user)throw new Error('Sign in first.');const payload={parent_id:state.user.id,slot,username,avatar_key:avatarKey};const {data,error}=await state.client.from('child_profiles').upsert(payload,{onConflict:'parent_id,slot'}).select().single();if(error)throw error;return data}
async function deleteChild(slot){if(!state.client||!state.user)throw new Error('Sign in first.');const {error}=await state.client.from('child_profiles').delete().eq('parent_id',state.user.id).eq('slot',slot);if(error)throw error}
async function loadProgress(childId){if(!state.client)return[];const {data,error}=await state.client.from('game_progress').select('world_key,highest_level,stars,updated_at').eq('child_profile_id',childId);if(error)throw error;return data||[]}
async function saveProgress(childId,worldKey,highestLevel,stars=0){if(!state.client)throw new Error('Backend is not configured yet.');const payload={child_profile_id:childId,world_key:worldKey,highest_level:Math.max(1,Math.min(30,highestLevel)),stars:Math.max(0,stars),updated_at:new Date().toISOString()};const {data,error}=await state.client.from('game_progress').upsert(payload,{onConflict:'child_profile_id,world_key'}).select().single();if(error)throw error;return data}
async function loadAchievements(childId){if(!state.client)return[];const {data,error}=await state.client.from('child_achievements').select('achievement_key,earned_at').eq('child_profile_id',childId).order('earned_at');if(error)throw error;return data||[]}
async function saveAchievement(childId,key){if(!state.client)throw new Error('Backend is not configured yet.');const {data,error}=await state.client.from('child_achievements').upsert({child_profile_id:childId,achievement_key:key},{onConflict:'child_profile_id,achievement_key'}).select().single();if(error)throw error;return data}
async function loadWorldBuild(childId){if(!state.client)return null;const {data,error}=await state.client.from('world_builds').select('child_profile_id,era,layout,resources,updated_at').eq('child_profile_id',childId).maybeSingle();if(error)throw error;return data||null}
async function saveWorldBuild(childId,era,layout,resources){if(!state.client)throw new Error('Backend is not configured yet.');const payload={child_profile_id:childId,era,layout:Array.isArray(layout)?layout:[],resources:Math.max(0,Math.min(9999,Number(resources)||0)),updated_at:new Date().toISOString()};const {data,error}=await state.client.from('world_builds').upsert(payload,{onConflict:'child_profile_id'}).select().single();if(error)throw error;return data}
async function entitlement(){if(!state.client||!state.user)return false;const {data,error}=await state.client.from('parent_accounts').select('lifetime_unlocked').eq('user_id',state.user.id).maybeSingle();if(error)throw error;return !!data?.lifetime_unlocked}
async function createCheckout(){if(!state.client||!state.user)throw new Error('Please sign in to the parent account first.');const {data,error}=await state.client.functions.invoke('create-revolut-order',{body:{}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
window.JamKarBackend={state,init,refreshUser,signUp,signIn,signOut,resetPassword,updatePassword,getFamily,setActiveChildSlot,saveChild,deleteChild,loadProgress,saveProgress,loadAchievements,saveAchievement,loadWorldBuild,saveWorldBuild,entitlement,createCheckout};
init().catch(err=>{console.error('JamKar backend init failed',err);emit('backend-error',{message:err.message})});
})();