(()=>{
'use strict';
const STORAGE_PREFIX='jamkar_custom_world|';
const THEME_META={
  water:{label:'Ocean World',emoji:'🌊',tagline:'Raise a living civilisation from coral gardens to a glowing deep-sea city.',accent:'#28c9d8'},
  prehistoric:{label:'Prehistoric World',emoji:'🦕',tagline:'Grow from a tiny survival camp into a thriving world beside ancient creatures.',accent:'#79c35a'},
  future:{label:'Future World',emoji:'🌆',tagline:'Build a clean, clever city of robots, skyways and renewable power.',accent:'#8a7dff'},
  mixed:{label:'Fusion World',emoji:'🌍',tagline:'Blend oceans, dinosaurs and future technology into one extraordinary world.',accent:'#ffb649'}
};
const PHASES=[
  {key:'spark',name:'First Spark',icon:'✨',need:2,era:'prehistoric'},
  {key:'home',name:'A Place to Live',icon:'🏕️',need:3,era:'settlement'},
  {key:'community',name:'Growing Community',icon:'🏘️',need:4,era:'ancient'},
  {key:'discovery',name:'Age of Discovery',icon:'🔭',need:4,era:'industrial'},
  {key:'harmony',name:'World in Harmony',icon:'🌿',need:5,era:'modern'},
  {key:'wonder',name:'World of Wonders',icon:'🌟',need:6,era:'future'}
];
const TASKS={
 water:[
  ['Clean the starter lagoon','Remove floating waste and choose what belongs in a healthy sea.','🧹'],['Plant the first coral garden','Pick a safe reef zone and restore coral habitat.','🪸'],['Create a fish nursery','Match young sea animals to the habitat they need.','🐠'],
  ['Build a research bubble','Use strong transparent materials for an underwater home.','🔬'],['Balance oxygen and food','Keep sea plants, animals and people in balance.','🌿'],['Protect a turtle route','Move hazards away from a migration path.','🐢'],
  ['Power a tide station','Choose renewable energy from tides and currents.','⚡'],['Map the trench','Read depth clues to open a safe exploration route.','🗺️'],['Grow a kelp farm','Design a farm that helps food, oxygen and wildlife.','🌱'],['Rescue a damaged reef','Repair the reef in the best ecological order.','🛟'],
  ['Launch a deep-sea lab','Complete a pressure and materials challenge.','🧪'],['Create a submarine route','Connect habitats without disturbing wildlife.','🚤'],['Build a glowing habitat','Use safe bioluminescent ideas to light the city.','💡'],['Study a mystery creature','Use clues to classify a deep-sea animal.','🦑'],
  ['Open the blue city','Plan homes, research, food and nature zones.','🏙️'],['Restore the ocean current','Solve a route puzzle to keep water moving.','🌀'],['Create a marine sanctuary','Choose which areas must stay protected.','🐋'],['Build a floating garden','Connect the deep city with the sunny surface.','🌺'],['Train ocean guardians','Complete a conservation mission.','🛡️'],
  ['Design the grand reef','Combine every skill to create a thriving reef.','👑'],['Build the abyss observatory','Create a safe window into the deepest zone.','🔭'],['Link every habitat','Build a transport network that protects nature.','🔗'],['Create the ocean festival','Celebrate science, art and sea life together.','🎉'],['Protect the world for tomorrow','Finish a sustainability plan for the whole ocean.','🌎']
 ],
 prehistoric:[
  ['Find fresh water','Follow landscape clues to locate a safe water source.','💧'],['Make the first shelter','Choose materials that keep the camp warm and dry.','⛺'],['Gather food safely','Sort useful plants and foods from unsafe choices.','🍓'],
  ['Light a safe campfire','Put the fire-building steps in the right order.','🔥'],['Track a herd','Read footprints and movement clues.','🐾'],['Protect the camp','Place barriers without harming nearby animals.','🪵'],
  ['Start a garden','Choose seeds and a sunny growing place.','🌱'],['Build a stronger home','Combine stone, wood and fibre for shelter.','🏠'],['Create a tool workshop','Match tools to the jobs they can safely do.','🪓'],['Map dinosaur territory','Plan a route that avoids nesting zones.','🦖'],
  ['Raise a village','Place homes, food and water around a shared centre.','🏘️'],['Study the fossils','Rebuild a skeleton from fossil clues.','🦴'],['Cross the river','Design a strong simple bridge.','🌉'],['Protect a hatchling','Build a safe wildlife corridor.','🥚'],
  ['Open the discovery camp','Create a place for learning, making and exploring.','🔎'],['Store food for winter','Plan supplies using simple number clues.','🧺'],['Create cave art','Build a visual story from symbols.','🎨'],['Make peace with nature','Balance people, plants and animals.','🌿'],['Explore the volcano valley','Choose the safest observation route.','🌋'],
  ['Build the great settlement','Combine all earlier systems into one thriving community.','👑'],['Create a fossil museum','Arrange discoveries into a learning trail.','🏛️'],['Restore the ancient forest','Plant a balanced habitat around the settlement.','🌲'],['Open the sky lookout','Use sun and stars to navigate.','🌌'],['Protect the next generation','Finish a long-term plan for people and wildlife.','🌍']
 ],
 future:[
  ['Power the first hub','Choose clean energy for your starter district.','🔋'],['Build a smart home','Connect light, water and temperature systems.','🏠'],['Program a helper robot','Put simple robot commands in the right order.','🤖'],
  ['Open a sky garden','Grow food above the city with less space.','🌱'],['Design clean transport','Choose routes that reduce traffic and pollution.','🚝'],['Recycle city materials','Sort materials into useful future resources.','♻️'],
  ['Build a learning lab','Create a space for science, coding and making.','🧪'],['Balance the power grid','Share energy between busy and quiet districts.','⚡'],['Create a drone corridor','Plan a safe route away from people and wildlife.','🛸'],['Open a robot workshop','Choose parts for different helpful jobs.','⚙️'],
  ['Grow the city centre','Place homes, parks, transport and services together.','🏙️'],['Clean the air','Use trees and technology to improve city air.','🌳'],['Build a water loop','Reuse and save water across the city.','💧'],['Solve the data network','Connect important systems without wasted links.','🔗'],
  ['Launch the moon gateway','Prepare energy, supplies and navigation.','🚀'],['Create a zero-waste district','Turn leftovers into new resources.','♻️'],['Build the learning tower','Create spaces for every kind of learner.','📚'],['Design a rescue robot','Choose sensors and tools for emergency support.','🦾'],['Protect city wildlife','Build green routes through the future city.','🦋'],
  ['Create the radiant capital','Combine every system into a beautiful future city.','👑'],['Open the orbital garden','Design a food system beyond Earth.','🛰️'],['Connect the skyways','Build a fast, clean transport network.','🌉'],['Create the invention festival','Showcase robots, science, music and art.','🎆'],['Plan the next century','Finish a long-term sustainable city plan.','🌎']
 ],
 mixed:[
  ['Choose the first safe island','Balance land, water and wildlife for a starter home.','🏝️'],['Restore a coral shore','Protect the coast before building nearby.','🪸'],['Meet the ancient neighbours','Study dinosaur clues and mark safe habitats.','🦕'],
  ['Build a solar camp','Mix simple shelter with clean future power.','☀️'],['Create a sea garden','Grow useful plants above and below the water.','🌱'],['Program a wildlife helper','Give a robot safe conservation instructions.','🤖'],
  ['Open a fossil reef lab','Compare clues from ancient land and modern sea life.','🔬'],['Build the first sky bridge','Connect two zones without damaging habitat.','🌉'],['Balance three ecosystems','Keep land, ocean and city resources healthy.','🌍'],['Create a rescue station','Prepare for storms, wildlife and exploration missions.','🛟'],
  ['Raise the fusion town','Combine prehistoric nature, ocean habitats and future homes.','🏘️'],['Power the tide gardens','Use ocean energy to support farms and homes.','⚡'],['Decode an ancient map','Use symbols and coordinates to find a discovery site.','🗺️'],['Build a robot submarine','Choose parts for exploration without disturbing animals.','🚤'],
  ['Open the time museum','Tell the story from prehistory to the future.','🏛️'],['Create the dinosaur sanctuary','Use modern technology to protect ancient-style habitats.','🦖'],['Build a floating future district','Design homes that live with the ocean.','🌆'],['Restore the great forest','Reconnect wild land around the growing civilisation.','🌲'],['Launch the star harbour','Connect your mixed world to space exploration.','🚀'],
  ['Create the living wonder world','Bring every biome and technology together beautifully.','👑'],['Open the deep-time observatory','Study ocean depths, fossils and stars together.','🔭'],['Connect every community','Build clean transport across land, sea and sky.','🔗'],['Create the world festival','Celebrate every era, habitat and invention.','🎉'],['Design the forever plan','Finish a balanced future for the entire world.','🌎']
 ]
};
const STRUCTURES={water:['🪸','🐠','🔬','🐢','⚡','🌿','🧪','🚤','🏙️','🐋','🔭','🌎'],prehistoric:['⛺','🔥','🦕','🌱','🏠','🪓','🦴','🌉','🏘️','🌲','🏛️','🌌'],future:['🔋','🏠','🤖','🌱','🚝','♻️','🧪','⚡','🏙️','🌳','🚀','🛰️'],mixed:['🏝️','🪸','🦕','☀️','🤖','🔬','🌉','🌍','🏘️','🚤','🌆','🚀']};
let world=null,root=null,cloudChild=null,saveTimer=null;
function key(){return STORAGE_PREFIX+(localStorage.getItem('jamkar_profile')||'Explorer')}
function blank(theme,name){return{version:1,theme,name:name||THEME_META[theme].label,completed:[],createdAt:Date.now(),updatedAt:Date.now()}}
function loadLocal(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
function saveLocal(){if(!world)return;world.updatedAt=Date.now();localStorage.setItem(key(),JSON.stringify(world));queueCloudSave()}
function phaseIndex(){let total=0;for(let i=0;i<PHASES.length;i++){total+=PHASES[i].need;if(world.completed.length<total)return i}return PHASES.length-1}
function tasksForWorld(){return TASKS[world.theme]||TASKS.mixed}
function currentTask(){return tasksForWorld()[Math.min(world.completed.length,tasksForWorld().length-1)]}
function phaseStart(i){return PHASES.slice(0,i).reduce((n,p)=>n+p.need,0)}
function phaseProgress(i){return Math.max(0,world.completed.length-phaseStart(i))}
function isFinished(){return world.completed.length>=tasksForWorld().length}
function buildShell(){if(root)return;root=document.createElement('section');root.className='cwShell';root.id='createWorldExperience';root.innerHTML=`<div class="cwTop"><button class="cwBack" type="button">← Adventures</button><div class="cwTitle"><span>CREATE YOUR OWN WORLD</span><strong>Build it by completing real missions</strong></div><button class="cwReset" type="button">New world</button></div><div class="cwBody"></div>`;document.body.appendChild(root);root.querySelector('.cwBack').onclick=close;root.querySelector('.cwReset').onclick=()=>{if(confirm('Start a new world? Your current custom world on this child profile will be replaced.')){world=null;localStorage.removeItem(key());renderChooser()}}}
function open(){buildShell();root.classList.add('open');document.body.classList.add('cw-open');const saved=loadLocal();if(saved?.theme&&THEME_META[saved.theme]){world=saved;renderWorld();syncFromCloud()}else renderChooser()}
function close(){root?.classList.remove('open');document.body.classList.remove('cw-open')}
function renderChooser(){world=null;root.querySelector('.cwBody').innerHTML=`<div class="cwChoose"><div class="cwChooseIntro"><span class="cwKicker">YOUR WORLD • NO LEVELS</span><h1>Where will your story begin?</h1><p>Choose a starting universe. Your world grows continuously as you finish missions, solve problems and unlock new places. There are no numbered levels and no finish line.</p></div><div class="cwThemeGrid">${Object.entries(THEME_META).map(([id,t])=>`<button class="cwThemeCard cw-${id}" data-theme="${id}"><span class="cwThemeEmoji">${t.emoji}</span><div><strong>${t.label}</strong><p>${t.tagline}</p></div><b>Choose world →</b></button>`).join('')}</div></div>`;root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>nameWorld(b.dataset.theme))}
function nameWorld(theme){const meta=THEME_META[theme];root.querySelector('.cwBody').innerHTML=`<div class="cwNaming cw-${theme}"><div class="cwNamePlanet"><span>${meta.emoji}</span></div><div class="cwNameCard"><span class="cwKicker">${meta.label}</span><h1>Name your new world</h1><p>${meta.tagline}</p><label>World name<input id="cwWorldName" maxlength="24" value="${meta.label.replace(' World','')}" autocomplete="off"></label><button class="primary" id="cwBegin">Create my world</button><button class="secondary" id="cwChooseAgain">Choose another theme</button></div></div>`;root.querySelector('#cwChooseAgain').onclick=renderChooser;root.querySelector('#cwBegin').onclick=()=>{const input=root.querySelector('#cwWorldName'),name=(input.value||'').trim().replace(/[<>]/g,'').slice(0,24);if(name.length<2){input.focus();return}world=blank(theme,name);saveLocal();renderWorld();cloudSave()}}
function renderWorld(){if(!world)return;const meta=THEME_META[world.theme],pi=phaseIndex(),phase=PHASES[pi],done=isFinished(),task=currentTask(),pDone=phaseProgress(pi),pct=done?100:Math.min(100,pDone/phase.need*100);root.querySelector('.cwBody').innerHTML=`<div class="cwWorld cw-${world.theme}" data-phase="${pi}"><div class="cwScene">${sceneMarkup(pi)}<div class="cwWorldName"><small>${meta.emoji} ${meta.label}</small><h1>${escapeHtml(world.name)}</h1><p>${done?'A living world that keeps growing with every new adventure.':phase.icon+' '+phase.name}</p></div><div class="cwGrowth"><span>World growth</span><div><i style="width:${Math.min(100,world.completed.length/tasksForWorld().length*100)}%"></i></div><b>${world.completed.length} missions completed</b></div></div><aside class="cwMission"><div class="cwPhaseHead"><span>${phase.icon}</span><div><small>DEVELOPMENT STAGE</small><h2>${done?'Living Wonder':phase.name}</h2></div></div><div class="cwPhaseBar"><i style="width:${pct}%"></i></div><small class="cwPhaseCount">${done?'World established':`${Math.min(pDone,phase.need)} of ${phase.need} requirements complete`}</small>${done?finishedMarkup():missionMarkup(task)}<div class="cwUnlocked"><h3>World discoveries</h3><div>${STRUCTURES[world.theme].slice(0,Math.max(2,Math.ceil(world.completed.length/2))).map((s,i)=>`<span style="--d:${i}">${s}</span>`).join('')}</div></div></aside></div>`;if(!done)root.querySelector('#cwCompleteTask').onclick=completeTask}
function missionMarkup(task){return `<div class="cwTask"><span class="cwTaskIcon">${task[2]}</span><small>NEXT WORLD REQUIREMENT</small><h2>${task[0]}</h2><p>${task[1]}</p><div class="cwTaskChecks"><span>✓ Explore</span><span>✓ Think</span><span>✓ Build</span></div><button id="cwCompleteTask" class="cwComplete" type="button">Complete mission & grow world</button></div>`}
function finishedMarkup(){return `<div class="cwTask cwCelebration"><span class="cwTaskIcon">🏆</span><small>YOUR WORLD IS ALIVE</small><h2>Keep developing forever</h2><p>You completed the founding requirements. Your world stays yours. Future mission packs can keep adding districts, creatures, inventions and discoveries without resetting it.</p></div>`}
function completeTask(){if(!world||isFinished())return;const idx=world.completed.length,task=tasksForWorld()[idx];world.completed.push({id:idx,title:task[0],at:Date.now()});saveLocal();const previous=phaseIndex();renderWorld();const current=phaseIndex();const shell=root.querySelector('.cwWorld');shell?.classList.add('cwGrowBurst');setTimeout(()=>shell?.classList.remove('cwGrowBurst'),900);if(current!==previous||isFinished())celebrate();else toast(`World grew! ${task[2]} ${task[0]} complete`)}
function celebrate(){const scene=root.querySelector('.cwScene');if(!scene)return;for(let i=0;i<34;i++){const p=document.createElement('i');p.className='cwConfetti';p.style.setProperty('--x',`${Math.random()*100}%`);p.style.setProperty('--r',`${Math.random()*320-160}deg`);p.style.setProperty('--delay',`${Math.random()*.45}s`);scene.appendChild(p);setTimeout(()=>p.remove(),2200)}toast(isFinished()?'Your world became a Living Wonder! 🌟':'New development stage unlocked! ✨')}
function sceneMarkup(){const s=STRUCTURES[world.theme],count=Math.min(s.length,2+Math.floor(world.completed.length/2)),items=s.slice(0,count).map((x,i)=>`<span class="cwStructure s${i%6}" style="--i:${i}">${x}</span>`).join('');return `<div class="cwSkyGlow"></div><div class="cwCloud c1"></div><div class="cwCloud c2"></div>${world.theme==='water'||world.theme==='mixed'?'<div class="cwWave w1"></div><div class="cwWave w2"></div><div class="cwBubbles"></div>':''}${world.theme==='prehistoric'||world.theme==='mixed'?'<div class="cwVolcano"><i></i></div><div class="cwFern f1">🌿</div><div class="cwFern f2">🌴</div>':''}${world.theme==='future'||world.theme==='mixed'?'<div class="cwSkyLane"><i></i><b>🛸</b></div><div class="cwNeonGrid"></div>':''}<div class="cwHorizon"></div><div class="cwStructures">${items}</div><div class="cwExplorer">🧒🏾</div><div class="cwAmbient a1">${world.theme==='water'?'🐠':world.theme==='prehistoric'?'🦕':world.theme==='future'?'🤖':'🐬'}</div><div class="cwAmbient a2">${world.theme==='water'?'🐢':world.theme==='prehistoric'?'🦖':world.theme==='future'?'🛰️':'🦕'}</div>`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._cw);t._cw=setTimeout(()=>t.classList.remove('show'),2500)}
async function resolveCloudChild(){try{const b=window.JamKarBackend;if(!b?.state?.user)return null;const fam=await b.getFamily();const profile=localStorage.getItem('jamkar_profile')||'Explorer';return fam?.children?.find(c=>c.username===profile)||fam?.children?.[0]||null}catch{return null}}
async function syncFromCloud(){const child=await resolveCloudChild();if(!child)return;cloudChild=child;try{const remote=await window.JamKarBackend.loadWorldBuild(child.id);const meta=remote?.layout?.find?.(x=>x?.kind==='custom-world-meta');if(meta?.theme&&THEME_META[meta.theme]){const remoteWorld={version:1,theme:meta.theme,name:meta.name||THEME_META[meta.theme].label,completed:Array.isArray(meta.completed)?meta.completed:[],createdAt:meta.createdAt||Date.now(),updatedAt:new Date(remote.updated_at||0).getTime()};if(!world||remoteWorld.updatedAt>(world.updatedAt||0)){world=remoteWorld;saveLocal();renderWorld()}}else if(world)cloudSave()}catch(e){console.warn('Custom world cloud load skipped',e)}}
function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(cloudSave,700)}
async function cloudSave(){if(!world)return;try{cloudChild=cloudChild||await resolveCloudChild();if(!cloudChild)return;const pi=phaseIndex(),layout=[{kind:'custom-world-meta',theme:world.theme,name:world.name,completed:world.completed,createdAt:world.createdAt,updatedAt:world.updatedAt}];await window.JamKarBackend.saveWorldBuild(cloudChild.id,PHASES[pi].era,layout,world.completed.length)}catch(e){console.warn('Custom world cloud save skipped',e)}}
function bindNavigation(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view="create"],[data-view="worlds"]');if(!b)return;e.preventDefault();open()})}
bindNavigation();window.JamKarCreateWorld={open,close};
})();