(()=>{
'use strict';
const STORAGE_PREFIX='jamkar_custom_world|';
const THEME_META={
 water:{label:'Ocean World',emoji:'🌊',tagline:'Raise a living civilisation from coral gardens to a glowing deep-sea city.'},
 prehistoric:{label:'Prehistoric World',emoji:'🦕',tagline:'Grow from a survival camp into a thriving world beside ancient creatures.'},
 future:{label:'Future World',emoji:'🌆',tagline:'Build a clean, clever city of robots, skyways and renewable power.'},
 mixed:{label:'Fusion World',emoji:'🌍',tagline:'Blend oceans, dinosaurs and future technology into one extraordinary world.'}
};
const PHASES=[['✨','First Spark',2,'prehistoric'],['🏕️','A Place to Live',3,'settlement'],['🏘️','Growing Community',4,'ancient'],['🔭','Age of Discovery',4,'industrial'],['🌿','World in Harmony',5,'modern'],['🌟','World of Wonders',6,'future']];
const TASKS={
 water:[
 ['Clean the starter lagoon','Remove floating waste while leaving sea life untouched.','🧹'],['Plant the first coral garden','Place young coral in the safest reef zones.','🪸'],['Create a fish nursery','Match young sea animals to safe habitat areas.','🐠'],['Build a research bubble','Choose strong materials and assemble the underwater lab.','🔬'],['Balance oxygen and food','Keep plants, animals and food resources in balance.','🌿'],['Protect a turtle route','Clear hazards from the turtle migration path.','🐢'],['Power a tide station','Connect the clean-energy route in the correct order.','⚡'],['Map the trench','Follow the safest depth route through the trench.','🗺️'],['Grow a kelp farm','Place kelp where light and water movement are best.','🌱'],['Rescue a damaged reef','Restore reef pieces in the correct recovery order.','🛟'],['Launch a deep-sea lab','Assemble a pressure-safe research station.','🧪'],['Create a submarine route','Connect habitats without crossing wildlife zones.','🚤'],['Build a glowing habitat','Choose a safe lighting system for the deep city.','💡'],['Study a mystery creature','Classify the creature from its clues.','🦑'],['Open the blue city','Balance homes, research, food and nature zones.','🏙️'],['Restore the ocean current','Reconnect the current through the correct channels.','🌀'],['Create a marine sanctuary','Mark the most important protection zones.','🐋'],['Build a floating garden','Place surface gardens where they help the city below.','🌺'],['Train ocean guardians','Complete a conservation response mission.','🛡️'],['Design the grand reef','Build a balanced reef with shelter, food and clean water.','👑'],['Build the abyss observatory','Assemble a safe deep-water observation station.','🔭'],['Link every habitat','Connect habitats with a wildlife-safe transport route.','🔗'],['Create the ocean festival','Arrange science, art and sea-life zones for the festival.','🎉'],['Protect the world for tomorrow','Choose the strongest long-term ocean plan.','🌎']
 ],
 prehistoric:[
 ['Find fresh water','Follow landscape clues to locate the safest water source.','💧'],['Make the first shelter','Build a warm, dry shelter from suitable materials.','⛺'],['Gather food safely','Collect useful foods and avoid unsafe items.','🍓'],['Light a safe campfire','Put the fire-building steps in the correct order.','🔥'],['Track a herd','Follow footprints without entering dangerous ground.','🐾'],['Protect the camp','Place barriers while keeping animal routes open.','🪵'],['Start a garden','Place seeds where sunlight and water are best.','🌱'],['Build a stronger home','Assemble stone, wood and fibre in the right places.','🏠'],['Create a tool workshop','Match tools to the jobs they can safely do.','🪓'],['Map dinosaur territory','Plot a safe route around nesting zones.','🦖'],['Raise a village','Balance homes, water, food and shared spaces.','🏘️'],['Study the fossils','Rebuild a fossil sequence from matching pieces.','🦴'],['Cross the river','Build a stable bridge from the available parts.','🌉'],['Protect a hatchling','Create a wildlife corridor to a safe habitat.','🥚'],['Open the discovery camp','Place learning, making and exploration zones.','🔎'],['Store food for winter','Choose enough supplies without wasting resources.','🧺'],['Create cave art','Arrange symbols into a clear story sequence.','🎨'],['Make peace with nature','Balance people, plants and animals.','🌿'],['Explore the volcano valley','Choose the safest observation route.','🌋'],['Build the great settlement','Combine shelter, food, water and learning areas.','👑'],['Create a fossil museum','Arrange discoveries into a clear visitor trail.','🏛️'],['Restore the ancient forest','Place trees and habitats to rebuild biodiversity.','🌲'],['Open the sky lookout','Follow the sun-and-stars navigation sequence.','🌌'],['Protect the next generation','Choose the strongest long-term people-and-wildlife plan.','🌍']
 ],
 future:[
 ['Power the first hub','Connect clean energy to the starter district.','🔋'],['Build a smart home','Assemble light, water and temperature systems.','🏠'],['Program a helper robot','Put robot commands in the correct order.','🤖'],['Open a sky garden','Place crops where light, water and space are balanced.','🌱'],['Design clean transport','Connect districts with the lowest-pollution route.','🚝'],['Recycle city materials','Sort materials into useful future resources.','♻️'],['Build a learning lab','Place science, coding and making zones.','🧪'],['Balance the power grid','Share energy between busy and quiet districts.','⚡'],['Create a drone corridor','Plot a safe route away from people and wildlife.','🛸'],['Open a robot workshop','Match robot parts to the jobs they perform.','⚙️'],['Grow the city centre','Balance homes, parks, transport and services.','🏙️'],['Clean the air','Choose the best mix of trees and clean technology.','🌳'],['Build a water loop','Connect capture, clean, reuse and storage systems.','💧'],['Solve the data network','Connect essential systems using the fewest safe links.','🔗'],['Launch the moon gateway','Prepare energy, supplies and navigation in order.','🚀'],['Create a zero-waste district','Sort leftovers into reuse, repair and recycling routes.','♻️'],['Build the learning tower','Arrange spaces for different kinds of learning.','📚'],['Design a rescue robot','Choose the correct sensors and tools.','🦾'],['Protect city wildlife','Build green routes through the future city.','🦋'],['Create the radiant capital','Balance every major city system.','👑'],['Open the orbital garden','Build a balanced food-and-water system beyond Earth.','🛰️'],['Connect the skyways','Plot a clean transport network between towers.','🌉'],['Create the invention festival','Arrange robots, science, music and art zones.','🎆'],['Plan the next century','Choose the strongest long-term sustainable city plan.','🌎']
 ],
 mixed:[
 ['Choose the first safe island','Balance land, water and wildlife for a starter home.','🏝️'],['Restore a coral shore','Clear hazards and restore coral before building.','🪸'],['Meet the ancient neighbours','Map safe dinosaur habitats around your settlement.','🦕'],['Build a solar camp','Assemble simple shelter with clean future power.','☀️'],['Create a sea garden','Place useful plants above and below the water.','🌱'],['Program a wildlife helper','Arrange robot commands for a conservation mission.','🤖'],['Open a fossil reef lab','Match ancient and ocean clues into groups.','🔬'],['Build the first sky bridge','Connect two zones without damaging habitat.','🌉'],['Balance three ecosystems','Balance land, ocean and city resources.','🌍'],['Create a rescue station','Choose tools for storms, wildlife and exploration.','🛟'],['Raise the fusion town','Balance prehistoric nature, ocean habitats and future homes.','🏘️'],['Power the tide gardens','Connect ocean energy to farms and homes.','⚡'],['Decode an ancient map','Follow symbols and coordinates to the discovery site.','🗺️'],['Build a robot submarine','Assemble the right parts for gentle exploration.','🚤'],['Open the time museum','Arrange eras from prehistory to the future.','🏛️'],['Create the dinosaur sanctuary','Place technology around protected ancient-style habitats.','🦖'],['Build a floating future district','Balance homes, gardens and ocean space.','🌆'],['Restore the great forest','Reconnect wild land around the civilisation.','🌲'],['Launch the star harbour','Prepare a route from land to orbit.','🚀'],['Create the living wonder world','Balance every biome and technology.','👑'],['Open the deep-time observatory','Link ocean, fossil and space observations.','🔭'],['Connect every community','Build clean routes across land, sea and sky.','🔗'],['Create the world festival','Arrange every era, habitat and invention.','🎉'],['Design the forever plan','Choose the strongest balanced future for the whole world.','🌎']
 ]
};
const STRUCTURES={water:['🪸','🐠','🔬','🐢','⚡','🌿','🧪','🚤','🏙️','🐋','🔭','🌎'],prehistoric:['⛺','🔥','🦕','🌱','🏠','🪓','🦴','🌉','🏘️','🌲','🏛️','🌌'],future:['🔋','🏠','🤖','🌱','🚝','♻️','🧪','⚡','🏙️','🌳','🚀','🛰️'],mixed:['🏝️','🪸','🦕','☀️','🤖','🔬','🌉','🌍','🏘️','🚤','🌆','🚀']};
let world=null,root=null,cloudChild=null,saveTimer=null,mission=null;
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function key(){return STORAGE_PREFIX+(localStorage.getItem('jamkar_profile')||'Explorer')}
function blank(theme,name){return{version:2,theme,name,completed:[],createdAt:Date.now(),updatedAt:Date.now()}}
function loadLocal(){try{return JSON.parse(localStorage.getItem(key())||'null')}catch{return null}}
function saveLocal(){if(!world)return;world.updatedAt=Date.now();localStorage.setItem(key(),JSON.stringify(world));queueCloudSave()}
function tasks(){return TASKS[world.theme]||TASKS.mixed}
function phaseIndex(){let total=0;for(let i=0;i<PHASES.length;i++){total+=PHASES[i][2];if(world.completed.length<total)return i}return PHASES.length-1}
function phaseStart(i){return PHASES.slice(0,i).reduce((n,p)=>n+p[2],0)}
function buildShell(){if(root)return;root=document.createElement('section');root.className='cwShell';root.id='createWorldExperience';root.innerHTML='<div class="cwTop"><button class="cwBack">← Adventures</button><div class="cwTitle"><span>CREATE YOUR OWN WORLD</span><strong>Grow it by playing missions</strong></div><button class="cwReset">New world</button></div><div class="cwBody"></div>';document.body.appendChild(root);root.querySelector('.cwBack').onclick=close;root.querySelector('.cwReset').onclick=()=>{if(confirm('Start a new world? This replaces the current custom world for this child profile.')){localStorage.removeItem(key());world=null;renderChooser()}}}
function open(){buildShell();root.classList.add('open');document.body.classList.add('cw-open');const saved=loadLocal();if(saved?.theme&&THEME_META[saved.theme]){world=saved;renderWorld();syncFromCloud()}else renderChooser()}
function close(){mission=null;root?.classList.remove('open');document.body.classList.remove('cw-open')}
function renderChooser(){root.querySelector('.cwBody').innerHTML=`<div class="cwChoose"><div class="cwChooseIntro"><span class="cwKicker">YOUR WORLD • NO LEVELS</span><h1>Where will your story begin?</h1><p>Your world develops continuously. Finish playable requirements to unlock buildings, wildlife, technology and new development stages.</p></div><div class="cwThemeGrid">${Object.entries(THEME_META).map(([id,t])=>`<button class="cwThemeCard cw-${id}" data-theme="${id}"><span class="cwThemeEmoji">${t.emoji}</span><div><strong>${t.label}</strong><p>${t.tagline}</p></div><b>Choose world →</b></button>`).join('')}</div></div>`;root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>nameWorld(b.dataset.theme))}
function nameWorld(theme){const t=THEME_META[theme];root.querySelector('.cwBody').innerHTML=`<div class="cwNaming cw-${theme}"><div class="cwNamePlanet"><span>${t.emoji}</span></div><div class="cwNameCard"><span class="cwKicker">${t.label}</span><h1>Name your new world</h1><p>${t.tagline}</p><label>World name<input id="cwWorldName" maxlength="24" value="${t.label.replace(' World','')}"></label><button class="primary" id="cwBegin">Create my world</button><button class="secondary" id="cwAgain">Choose another theme</button></div></div>`;root.querySelector('#cwAgain').onclick=renderChooser;root.querySelector('#cwBegin').onclick=()=>{const n=root.querySelector('#cwWorldName').value.trim().replace(/[<>]/g,'').slice(0,24);if(n.length<2)return;world=blank(theme,n);saveLocal();renderWorld()}}
function renderWorld(){if(!world)return;const pi=phaseIndex(),p=PHASES[pi],finished=world.completed.length>=tasks().length,task=tasks()[Math.min(world.completed.length,tasks().length-1)],stageDone=Math.max(0,world.completed.length-phaseStart(pi));root.querySelector('.cwBody').innerHTML=`<div class="cwWorld cw-${world.theme}" data-phase="${pi}"><div class="cwScene">${sceneMarkup(pi)}<div class="cwWorldName"><small>${THEME_META[world.theme].emoji} ${THEME_META[world.theme].label}</small><h1>${esc(world.name)}</h1><p>${finished?'A living world that can keep growing.':p[0]+' '+p[1]}</p></div><div class="cwGrowth"><span>World growth</span><div><i style="width:${Math.min(100,world.completed.length/tasks().length*100)}%"></i></div><b>${world.completed.length} missions completed</b></div></div><aside class="cwMission"><div class="cwPhaseHead"><span>${p[0]}</span><div><small>DEVELOPMENT STAGE</small><h2>${finished?'Living Wonder':p[1]}</h2></div></div><div class="cwPhaseBar"><i style="width:${finished?100:Math.min(100,stageDone/p[2]*100)}%"></i></div><small class="cwPhaseCount">${finished?'World established':`${Math.min(stageDone,p[2])} of ${p[2]} requirements complete`}</small>${finished?finishedMarkup():missionCard(task)}<div class="cwUnlocked"><h3>World discoveries</h3><div>${STRUCTURES[world.theme].slice(0,Math.max(2,Math.ceil(world.completed.length/2))).map((s,i)=>`<span style="--d:${i}">${s}</span>`).join('')}</div></div></aside></div>`;if(!finished)root.querySelector('#cwPlayMission').onclick=()=>launchMission(task)}
function missionCard(t){return `<div class="cwTask"><span class="cwTaskIcon">${t[2]}</span><small>NEXT WORLD REQUIREMENT</small><h2>${t[0]}</h2><p>${t[1]}</p><div class="cwTaskChecks"><span>🎮 Play</span><span>🧠 Think</span><span>🏗️ Grow</span></div><button id="cwPlayMission" class="cwComplete">Play mission</button></div>`}
function finishedMarkup(){return `<div class="cwTask cwCelebration"><span class="cwTaskIcon">🏆</span><small>YOUR WORLD IS ALIVE</small><h2>Keep developing</h2><p>You completed the current development journey. New missions can be added without numbered levels.</p></div>`}
function sceneMarkup(pi){const s=STRUCTURES[world.theme],count=Math.min(s.length,2+Math.ceil(world.completed.length/2));return `<div class="cwSky"></div><div class="cwTerrain"></div><div class="cwAtmosphere">${Array.from({length:10},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="cwBuilds">${s.slice(0,count).map((x,i)=>`<span style="--x:${8+(i*13)%78}%;--y:${47+(i%3)*14}%;--d:${i}">${x}</span>`).join('')}</div>`}
function missionType(title){const t=title.toLowerCase();if(/clean|gather|recycle|restore|protect|rescue/.test(t))return'collect';if(/route|map|track|connect|network|current|skyway|navigate|launch/.test(t))return'route';if(/build|plant|grow|create|raise|open|design|assemble/.test(t))return'build';if(/program|sequence|light|decode|study|classify|arrange/.test(t))return'sequence';return'balance'}
function launchMission(task){mission={task,type:missionType(task[0]),score:0,step:0,lives:3,selected:[]};renderMissionGame()}
function renderMissionGame(){const m=mission,t=m.task,type=m.type;root.querySelector('.cwBody').innerHTML=`<div class="cwPlay cw-${world.theme}"><div class="cwPlayTop"><button id="cwExitMission">← World</button><div><small>WORLD REQUIREMENT</small><h2>${t[2]} ${t[0]}</h2></div><span class="cwLives">${'❤️'.repeat(m.lives)}</span></div><div class="cwPlayArena"><div class="cwMissionPrompt">${promptFor(type,t)}</div><div class="cwMiniGame" id="cwMiniGame"></div></div></div>`;root.querySelector('#cwExitMission').onclick=renderWorld;renderMechanic()}
function promptFor(type,t){return({collect:'Tap the correct moving items. Avoid the things that belong in the habitat.',route:'Connect the checkpoints in the safest order.',build:'Choose useful pieces and place them into the world.',sequence:'Put the actions in the correct order.',balance:'Choose the three decisions that keep the world balanced.'})[type]+` <b>${t[1]}</b>`}
function renderMechanic(){const box=root.querySelector('#cwMiniGame'),m=mission,t=m.task;if(m.type==='collect')renderCollect(box,t);else if(m.type==='route')renderRoute(box,t);else if(m.type==='build')renderBuild(box,t);else if(m.type==='sequence')renderSequence(box,t);else renderBalance(box,t)}
function themeSet(){return{water:{good:['🧴','🥤','🗑️','🧹'],bad:['🐠','🐢','🪸']},prehistoric:{good:['💧','🍓','🪵','🪨'],bad:['☠️','🌋','🦖']},future:{good:['🔋','♻️','🌳','💧'],bad:['💨','🗑️','⚠️']},mixed:{good:['☀️','🪸','🌱','🤖'],bad:['☠️','💨','🗑️']}}[world.theme]}
function renderCollect(box){const set=themeSet(),items=[...set.good.slice(0,3).map(x=>[x,1]),...set.bad.slice(0,3).map(x=>[x,0])].sort(()=>Math.random()-.5);box.innerHTML=`<div class="cwCollectHud"><b>${mission.score}/3 found</b><span>Choose only helpful targets</span></div><div class="cwCollectField">${items.map((a,i)=>`<button class="cwMovingItem" style="--i:${i};--x:${12+i*14}%" data-good="${a[1]}">${a[0]}</button>`).join('')}</div>`;box.querySelectorAll('.cwMovingItem').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;if(b.dataset.good==='1'){b.classList.add('good');mission.score++;if(mission.score>=3)return missionWin()}else{b.classList.add('bad');loseLife()}box.querySelector('.cwCollectHud b').textContent=`${mission.score}/3 found`})}
function renderRoute(box){const labels=world.theme==='water'?['Reef','Current','Lab','City']:world.theme==='prehistoric'?['Camp','River','Ridge','Valley']:world.theme==='future'?['Hub','Garden','Tower','Gateway']:['Island','Reef','Forest','Skyport'];box.innerHTML=`<div class="cwRouteMap">${labels.map((x,i)=>`<button data-step="${i}" style="--x:${12+i*25}%;--y:${i%2?65:28}%"><span>${i+1}</span>${x}</button>`).join('')}<svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="12,28 37,65 62,28 87,65"/></svg></div><p class="cwMiniHint">Visit checkpoints 1 → 2 → 3 → 4.</p>`;box.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.step);if(n===mission.step){b.classList.add('done');mission.step++;if(mission.step===4)missionWin()}else{b.classList.add('wrong');loseLife()}})}
function renderBuild(box){const pieces=STRUCTURES[world.theme].slice(0,6);box.innerHTML=`<div class="cwBuildTray">${pieces.map((p,i)=>`<button data-piece="${i}">${p}<small>${['Home','Nature','Power','Learning','Transport','Community'][i]}</small></button>`).join('')}</div><div class="cwBuildSlots">${[0,1,2].map(i=>`<button data-slot="${i}"><span>+</span><small>Place piece</small></button>`).join('')}</div><p class="cwMiniHint">Choose a piece, then choose an empty place. Build 3 useful features.</p>`;let selected=null;box.querySelectorAll('[data-piece]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-piece]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b});box.querySelectorAll('[data-slot]').forEach(s=>s.onclick=()=>{if(!selected||s.dataset.done)return;s.dataset.done='1';s.innerHTML=`<strong>${pieces[Number(selected.dataset.piece)]}</strong><small>Built!</small>`;s.classList.add('done');mission.score++;selected.classList.add('used');selected=null;if(mission.score===3)missionWin()})}
function renderSequence(box){const sets={water:['Observe','Plan','Restore','Protect'],prehistoric:['Gather','Prepare','Build','Check'],future:['Scan','Program','Test','Launch'],mixed:['Explore','Balance','Build','Protect']};const seq=sets[world.theme],shuffled=seq.map((v,i)=>[v,i]).sort(()=>Math.random()-.5);box.innerHTML=`<div class="cwSequence">${shuffled.map(([v,i])=>`<button data-order="${i}"><span>${v}</span><small>Tap next</small></button>`).join('')}</div><p class="cwMiniHint">Build the correct four-step plan.</p>`;box.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.order);if(n===mission.step){b.classList.add('done');b.disabled=true;mission.step++;if(mission.step===4)missionWin()}else{b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350);loseLife()}})}
function renderBalance(box){const choices=world.theme==='water'?[['Protect habitat',1],['Dump waste',0],['Use clean energy',1],['Overfish',0],['Save water',1],['Block migration',0]]:world.theme==='prehistoric'?[['Share water',1],['Destroy habitat',0],['Store food',1],['Protect wildlife route',1],['Waste supplies',0],['Build on nests',0]]:world.theme==='future'?[['Renewable power',1],['Dirty fuel',0],['Green transport',1],['Reuse water',1],['Waste resources',0],['Remove every tree',0]]:[['Protect reef',1],['Solar power',1],['Wildlife corridor',1],['Pollute river',0],['Block habitat',0],['Waste energy',0]];box.innerHTML=`<div class="cwBalance">${choices.sort(()=>Math.random()-.5).map((c,i)=>`<button data-good="${c[1]}" data-id="${i}">${c[0]}</button>`).join('')}</div><div class="cwBalanceMeter"><i style="width:0"></i><span>0 / 3 balanced choices</span></div>`;box.querySelectorAll('.cwBalance button').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;if(b.dataset.good==='1'){b.classList.add('good');mission.score++;box.querySelector('.cwBalanceMeter i').style.width=`${mission.score/3*100}%`;box.querySelector('.cwBalanceMeter span').textContent=`${mission.score} / 3 balanced choices`;if(mission.score===3)missionWin()}else{b.classList.add('bad');loseLife()}})}
function loseLife(){mission.lives--;const l=root.querySelector('.cwLives');if(l)l.textContent='❤️'.repeat(Math.max(0,mission.lives));if(mission.lives<=0)setTimeout(()=>missionFail(),300)}
function missionFail(){const box=root.querySelector('#cwMiniGame');if(!box)return;box.innerHTML=`<div class="cwMissionResult"><span>🌱</span><h2>Try that mission again</h2><p>Your world only grows when the requirement is completed.</p><button id="cwRetry" class="cwComplete">Try again</button></div>`;root.querySelector('#cwRetry').onclick=()=>launchMission(mission.task)}
function missionWin(){const task=mission.task;const box=root.querySelector('#cwMiniGame');if(!box)return;box.innerHTML=`<div class="cwMissionResult success"><span>✨</span><h2>Requirement complete!</h2><p>${task[2]} ${task[0]} is now part of ${esc(world.name)}.</p><button id="cwGrow" class="cwComplete">Grow my world</button></div>`;root.querySelector('#cwGrow').onclick=()=>{const idx=world.completed.length;if(!world.completed.includes(idx))world.completed.push(idx);saveLocal();mission=null;renderWorld();burst()}}
function burst(){if(!root)return;for(let i=0;i<18;i++){const s=document.createElement('i');s.className='cwBurst';s.textContent=['✨','⭐','🌟'][i%3];s.style.setProperty('--x',`${20+Math.random()*60}vw`);s.style.setProperty('--y',`${20+Math.random()*50}vh`);root.appendChild(s);setTimeout(()=>s.remove(),1300)}}
async function syncFromCloud(){try{const b=window.JamKarBackend;if(!b?.state?.user)return;const family=await b.getFamily();const profile=localStorage.getItem('jamkar_profile');cloudChild=(family?.children||[]).find(c=>c.username===profile)||(family?.children||[])[0];if(!cloudChild)return;const saved=await b.loadWorldBuild(cloudChild.id);const remote=saved?.layout?.[0]?.customWorld;if(remote?.theme&&(!world||Number(remote.updatedAt)>Number(world.updatedAt))){world=remote;saveLocal();renderWorld()}}catch(e){console.warn('Custom world cloud load skipped',e)}}
function queueCloudSave(){clearTimeout(saveTimer);saveTimer=setTimeout(cloudSave,500)}
async function cloudSave(){try{const b=window.JamKarBackend;if(!world||!b?.state?.user)return;if(!cloudChild){const family=await b.getFamily();const profile=localStorage.getItem('jamkar_profile');cloudChild=(family?.children||[]).find(c=>c.username===profile)||(family?.children||[])[0]}if(!cloudChild)return;const era=PHASES[phaseIndex()][3];await b.saveWorldBuild(cloudChild.id,era,[{customWorld:world}],Math.min(9999,world.completed.length*10+20))}catch(e){console.warn('Custom world cloud save skipped',e)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;if(['create','worlds'].includes(b.dataset.view)){e.preventDefault();open()}});window.addEventListener('jamkar:auth',()=>{cloudChild=null;if(root?.classList.contains('open'))syncFromCloud()})}
bind();window.JamKarCreateWorld={open,close};
})();