(()=>{
const completed=JSON.parse(localStorage.getItem('jamkar_completed')||'{}');
const achievements=JSON.parse(localStorage.getItem('jamkar_achievements')||'{}');
const originalStartLevel=startLevel;

function saveExtras(){localStorage.setItem('jamkar_completed',JSON.stringify(completed));localStorage.setItem('jamkar_achievements',JSON.stringify(achievements));}
function worldKey(){return state.activeProfile+'|'+state.selected.name}
function award(name){const key=state.activeProfile;achievements[key]=achievements[key]||[];if(!achievements[key].includes(name)){achievements[key].push(name);saveExtras();toast('Achievement unlocked: '+name+' 🏆')}}
function completeLevel(message='Level complete! ✨'){
  const key=worldKey();
  const current=state.selectedLevel;
  if(current>=30){state.progress[key]=30;completed[key]=true;award(state.selected.name+' Master');save();saveExtras();renderStats();renderWorlds();renderLevels();showVictory();return}
  state.progress[key]=Math.max(progressFor(state.selected.name),current+1);
  if(current===3)award('Starter Explorer');
  if(current===10)award('Level 10 Adventurer');
  if(current===20)award('Level 20 Pathfinder');
  save();renderStats();renderWorlds();renderLevels();
  const fb=document.querySelector('#feedback');if(fb)fb.textContent=message;
  setTimeout(()=>{if(!state.paid&&current===3){els.modal.classList.remove('open');openAccount('unlock')}else{startLevel(current+1)}},650);
}
function showVictory(){els.stage.innerHTML=`<div class="victory"><div class="victoryIcon">🏆</div><h3>${state.selected.name} complete!</h3><div class="badgeBurst"><span class="achievement">30 / 30 levels</span><span class="achievement">World Master</span></div><p>${state.activeProfile} has completed every level in this world. Choose another world to continue the JamKar adventure.</p><div class="gameActions"><button class="primary" id="replay30">Replay Level 30</button><button class="secondary" id="backWorlds">Choose another world</button></div></div>`;document.querySelector('#replay30').onclick=()=>startLevel(30);document.querySelector('#backWorlds').onclick=()=>els.modal.classList.remove('open')}

answer=function(btn,pick,correct){document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);let fb=document.querySelector('#feedback');if(pick===correct){btn.classList.add('correct');if(fb)fb.textContent='Excellent! Level complete. ✨';setTimeout(()=>completeLevel(),350)}else{btn.classList.add('wrong');document.querySelector(`[data-answer="${correct}"]`)?.classList.add('correct');if(fb)fb.textContent='Good try. Check the highlighted answer, then try again.';setTimeout(()=>{document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=false);btn.classList.remove('wrong');document.querySelector(`[data-answer="${correct}"]`)?.classList.remove('correct')},850)}};

function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function memoryGame(n){const pool=['🦖','🚀','🐋','🌟','🧠','🏺','🌈','🤖','🦁','🪐'];const pairs=Math.min(6,2+Math.floor((n-1)/6));const icons=pool.slice(0,pairs);const cards=shuffle([...icons,...icons]);let open=[];let matched=0;els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Memory · Level ${n}</div><h3>Match the hidden pairs</h3><p class="gameHint">Turn over two cards. Remember where each symbol is and match every pair.</p><div class="memoryGrid">${cards.map((x,i)=>`<button class="memoryCard" data-i="${i}" data-v="${x}" aria-label="Memory card ${i+1}">${x}</button>`).join('')}</div><p class="note" id="feedback">Pairs found: 0 / ${pairs}</p></div>`;document.querySelectorAll('.memoryCard').forEach(c=>c.onclick=()=>{if(c.classList.contains('flipped')||c.classList.contains('matched')||open.length===2)return;c.classList.add('flipped');open.push(c);if(open.length===2){const[a,b]=open;if(a.dataset.v===b.dataset.v){a.classList.add('matched');b.classList.add('matched');open=[];matched++;document.querySelector('#feedback').textContent=`Pairs found: ${matched} / ${pairs}`;if(matched===pairs)setTimeout(()=>completeLevel('Memory mission complete! 🧠'),450)}else setTimeout(()=>{a.classList.remove('flipped');b.classList.remove('flipped');open=[]},650)}})}

function codeGame(n){const sets=[['START','MOVE →','MOVE →','GOAL'],['START','MOVE ↑','TURN →','MOVE →','GOAL'],['START','MOVE →','LOOP ×2','MOVE ↑','GOAL']];const target=sets[Math.min(sets.length-1,Math.floor((n-1)/10))];const bank=shuffle(target.map((x,i)=>({x,id:i})));let chosen=[];els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Coding · Level ${n}</div><h3>Build the command sequence</h3><p class="gameHint">Tap the commands in the correct order so the robot can reach its goal.</p><div class="commandTrack" id="commandTrack"><span class="note">Your program appears here</span></div><div class="commandBank">${bank.map((o,i)=>`<button class="commandBtn" data-cmd="${i}" data-label="${o.x}">${o.x}</button>`).join('')}</div><div class="gameActions"><button class="secondary" id="resetCode">Reset</button><button class="primary" id="runCode">Run program</button></div><p class="note" id="feedback">Arrange all ${target.length} commands.</p></div>`;const render=()=>{document.querySelector('#commandTrack').innerHTML=chosen.length?chosen.map(x=>`<span class="commandToken">${x}</span>`).join(''):'<span class="note">Your program appears here</span>'};document.querySelectorAll('.commandBtn').forEach(b=>b.onclick=()=>{chosen.push(b.dataset.label);b.classList.add('used');render()});document.querySelector('#resetCode').onclick=()=>{chosen=[];document.querySelectorAll('.commandBtn').forEach(b=>b.classList.remove('used'));render()};document.querySelector('#runCode').onclick=()=>{if(chosen.join('|')===target.join('|'))completeLevel('Program successful! Robot reached the goal. 🤖');else document.querySelector('#feedback').textContent='Not quite. Reset and check the order of your commands.'}}

function ecoGame(n){const good=['♻️','🪴','🚲','💧','🌳','🔋','🧴'];const bad=['🗑️','🛢️','🚗💨','🔥','🥤','🧯'];const total=Math.min(12,6+Math.floor(n/5));let score=0,hits=0;const items=shuffle(Array.from({length:total},(_,i)=>i%3===0?{v:bad[i%bad.length],good:false}:{v:good[i%good.length],good:true}));els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Eco Rescue · Level ${n}</div><h3>Rescue the planet</h3><p class="gameHint">Tap actions and objects that help the environment. Avoid harmful choices.</p><div class="ecoScore" id="ecoScore">Eco points: 0</div><div class="ecoBoard">${items.map((o,i)=>`<button class="ecoItem" data-eco="${i}" data-good="${o.good}">${o.v}</button>`).join('')}</div><p class="note" id="feedback">Find every planet-friendly choice.</p></div>`;const target=items.filter(x=>x.good).length;document.querySelectorAll('.ecoItem').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;hits++;if(b.dataset.good==='true'){score++;b.classList.add('good')}else b.classList.add('bad');document.querySelector('#ecoScore').textContent=`Eco points: ${score} / ${target}`;if(hits===items.length){if(score>=Math.ceil(target*.75))setTimeout(()=>completeLevel('Eco mission complete! 🌍'),350);else{document.querySelector('#feedback').textContent='Try again and choose more planet-friendly actions.';setTimeout(()=>ecoGame(n),900)}}})}

function builderGame(n){const buildings=[{e:'⛺',name:'Shelter',cost:1},{e:'💧',name:'Water',cost:1},{e:'🌾',name:'Food',cost:1},{e:'🏠',name:'Home',cost:2},{e:'🏫',name:'School',cost:2},{e:'⚡',name:'Energy',cost:2},{e:'🏙️',name:'City',cost:3},{e:'🚀',name:'Future',cost:3}];let energy=6+Math.floor(n/4),selected=0,placed=0;const goal=Math.min(8,3+Math.floor(n/5));els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">World Builder · Level ${n}</div><h3>Build a thriving settlement</h3><div class="resourceBar"><span class="resourcePill" id="energy">⚙️ Resources: ${energy}</span><span class="resourcePill">🎯 Goal: ${goal} buildings</span></div><div class="builderWrap"><div class="builderGrid">${Array.from({length:16},(_,i)=>`<button class="builderCell" data-cell="${i}"></button>`).join('')}</div><div class="buildPalette">${buildings.map((b,i)=>`<button class="buildTile ${i===0?'active':''}" data-build="${i}">${b.e} ${b.name}<br><small>${b.cost} resource${b.cost>1?'s':''}</small></button>`).join('')}</div></div><p class="note" id="feedback">Place ${goal} buildings before your resources run out.</p></div>`;document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.build);document.querySelectorAll('[data-build]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-cell]').forEach(cell=>cell.onclick=()=>{if(cell.classList.contains('filled'))return;const b=buildings[selected];if(energy<b.cost){document.querySelector('#feedback').textContent='Not enough resources for that building. Choose a cheaper option.';return}energy-=b.cost;placed++;cell.textContent=b.e;cell.classList.add('filled');document.querySelector('#energy').textContent='⚙️ Resources: '+energy;if(placed>=goal)setTimeout(()=>completeLevel('Your civilisation is growing! 🏗️'),350);else if(energy===0)document.querySelector('#feedback').textContent='Resources used up. Replay and plan a cheaper settlement.'})}

function raceGame(n){let hits=0;const needed=Math.min(7,3+Math.floor(n/6));let active=true;els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Reaction Challenge · Level ${n}</div><h3>Catch the energy gates</h3><p class="gameHint">Tap each glowing gate quickly. The target moves after every successful hit.</p><div class="raceZone" id="raceZone"><button class="raceGate" id="raceGate">⚡</button></div><div class="raceStatus" id="raceStatus">Gates: 0 / ${needed}</div></div>`;const zone=document.querySelector('#raceZone'),gate=document.querySelector('#raceGate');const move=()=>{const maxX=Math.max(0,zone.clientWidth-80),maxY=Math.max(0,zone.clientHeight-80);gate.style.left=Math.floor(Math.random()*maxX)+'px';gate.style.top=Math.floor(Math.random()*maxY)+'px'};gate.onclick=()=>{if(!active)return;hits++;document.querySelector('#raceStatus').textContent=`Gates: ${hits} / ${needed}`;if(hits>=needed){active=false;completeLevel('Reaction mission complete! 🛸')}else move()};move()}

startLevel=function(n){state.selectedLevel=n;if(completed[worldKey()]&&n===30){showVictory();return}switch(state.selected.name){case'Memory Islands':memoryGame(n);break;case'Code Crew':codeGame(n);break;case'Eco Rescue':ecoGame(n);break;case'Time Builder':builderGame(n);break;case'Sky Racers':raceGame(n);break;default:originalStartLevel(n)}};

const oldSave=document.querySelector('#saveProfiles');if(oldSave){oldSave.onclick=()=>{const p1=document.querySelector('#child1').value.trim();const p2=document.querySelector('#child2').value.trim();const valid=/^[A-Za-z0-9_-]{3,18}$/;let err=document.querySelector('#profileError');if(!err){err=document.createElement('div');err.id='profileError';err.className='profileError';oldSave.insertAdjacentElement('afterend',err)}err.textContent='';if(!valid.test(p1)){err.textContent='Profile 1 must be 3–18 characters using letters, numbers, _ or -.';return}if(p2&&!valid.test(p2)){err.textContent='Profile 2 must be 3–18 characters using letters, numbers, _ or -.';return}if(p2&&p1.toLowerCase()===p2.toLowerCase()){err.textContent='The two child usernames must be different.';return}const profiles=[p1,p2].filter(Boolean);localStorage.setItem('jamkar_profiles',JSON.stringify(profiles));state.activeProfile=p1;save();loadProfiles();renderStats();renderWorlds();toast('Child profiles saved on this device.')}}
})();