(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const themes={
'Dino Frontier':{sky:['#bff3ff','#dfffb9'],ground:'#77b95f',accent:'#5f9a48',collect:'🦴',goal:'⛺',npcs:['🦕','🦖','🦤'],props:['🌴','🌿','🪨']},
'Deep Ocean':{sky:['#7ee5f5','#0e6ea7'],ground:'#0a4e79',accent:'#2eb5c9',collect:'🐚',goal:'⚓',npcs:['🐠','🐢','🐬'],props:['🪸','🌿','🪨']},
'Ancient Worlds':{sky:['#ffe9a7','#f1bd68'],ground:'#c9974f',accent:'#8e6738',collect:'🏺',goal:'🏛️',npcs:['🐪','🦅','🐈'],props:['🌴','🗿','🧱']},
'Wild Planet':{sky:['#c7f4b6','#75c77c'],ground:'#4d975c',accent:'#2e713f',collect:'🔎',goal:'🏕️',npcs:['🦁','🦓','🐘'],props:['🌳','🌾','🪨']},
'Deep Space':{sky:['#312e81','#090b24'],ground:'#1d2141',accent:'#665be8',collect:'⭐',goal:'🚀',npcs:['🛸','🤖','🛰️'],props:['🌌','☄️','🪨']},
'Future City':{sky:['#bce9ff','#8597ff'],ground:'#56698e',accent:'#6d7ef2',collect:'⚡',goal:'🏢',npcs:['🤖','🚕','🛸'],props:['🏙️','🌳','🚦']},
'Word Quest':{sky:['#ffe7f2','#e7d2ff'],ground:'#ba79a2',accent:'#d55a9d',collect:'🔤',goal:'📖',npcs:['🦉','✏️','📚'],props:['📝','🪶','📚']},
'Math Galaxy':{sky:['#ffdca8','#8068ea'],ground:'#514284',accent:'#f49a3d',collect:'⭐',goal:'🪐',npcs:['🤖','➗','✖️'],props:['🔺','🔷','🧮']},
'Science Lab':{sky:['#caffea','#9adbf5'],ground:'#5a9e96',accent:'#49b492',collect:'🧬',goal:'🔬',npcs:['🤖','🧬','⚛️'],props:['🧪','⚗️','🧫']},
'Puzzle Temple':{sky:['#ffe6ac','#d99155'],ground:'#8c6040',accent:'#b77745',collect:'🗝️',goal:'🏯',npcs:['🦉','🗿','🔮'],props:['🧩','🗿','🔷']},
'Eco Rescue':{sky:['#d3ffd4','#7edca4'],ground:'#4b9d69',accent:'#2f8250',collect:'♻️',goal:'🌍',npcs:['🐼','🐢','🦜'],props:['🌳','🌻','💧']},
'Code Crew':{sky:['#b9c8ff','#364a8f'],ground:'#27365f',accent:'#5573d5',collect:'💾',goal:'🖥️',npcs:['🤖','👾','🛰️'],props:['🔌','📡','💻']},
'Time Builder':{sky:['#ffe5b7','#b8e2ff'],ground:'#a57b50',accent:'#c28c52',collect:'🧱',goal:'🏰',npcs:['👷','🚜','🤖'],props:['🏠','⚙️','🪵']},
'Sky Racers':{sky:['#c7edff','#8ebcff'],ground:'#7ba8ca',accent:'#5295cf',collect:'🏁',goal:'🏆',npcs:['🛩️','🛸','🚁'],props:['☁️','🎈','⚡']},
'Memory Islands':{sky:['#d8f5ff','#a989eb'],ground:'#6f8eb1',accent:'#7b61c7',collect:'💎',goal:'🏝️',npcs:['🦜','🐒','🐬'],props:['🌴','🗿','🌺']},
'World Explorer':{sky:['#c9ffe8','#8fd9ff'],ground:'#69a67b',accent:'#3b9470',collect:'📍',goal:'🌐',npcs:['🚌','🛶','🚲'],props:['🏔️','🏝️','🏙️']},
'Music Makers':{sky:['#ffd8f0','#d4c7ff'],ground:'#9d6aa3',accent:'#d95ca5',collect:'🎵',goal:'🎤',npcs:['🥁','🎺','🎹'],props:['🎶','🎧','🎤']},
'Art Studio':{sky:['#ffe0c7','#ffd7ef'],ground:'#c4877c',accent:'#ea7c62',collect:'🎨',goal:'🖼️',npcs:['🖌️','🖍️','✏️'],props:['🎨','🖼️','🪄']},
'Weather Watch':{sky:['#d9f4ff','#9dcbe9'],ground:'#73a4b8',accent:'#5fa6c7',collect:'🌡️',goal:'📡',npcs:['🌧️','🌪️','☀️'],props:['☁️','🌈','💧']},
'Engineering Bay':{sky:['#dce7ff','#a5b9d8'],ground:'#61738e',accent:'#6f8db5',collect:'🔩',goal:'🏭',npcs:['🤖','🚜','🦾'],props:['⚙️','🔧','📐']},
'Language Lab':{sky:['#ffe4dc','#ffd9f1'],ground:'#b77c78',accent:'#e07160',collect:'💬',goal:'🗣️',npcs:['🦜','🤖','📣'],props:['🔤','📚','🎧']},
'Mystery Maze':{sky:['#c8b9f0','#51426f'],ground:'#463956',accent:'#8068b8',collect:'🗝️',goal:'🏁',npcs:['🦉','👻','🔮'],props:['🕯️','🚪','🧩']},
'Garden Guardians':{sky:['#e5ffc7','#a5e789'],ground:'#69a954',accent:'#5b9d43',collect:'🌱',goal:'🌳',npcs:['🐝','🦋','🐞'],props:['🌻','🌷','💧']},
'Robot Factory':{sky:['#dce8f4','#8ca7bf'],ground:'#526778',accent:'#6c91ae',collect:'🔩',goal:'🤖',npcs:['🤖','🦾','🚚'],props:['⚙️','🔋','📦']}
};
let engine=null,keys=new Set();
function worldName(){try{return state?.selected?.name||''}catch{return''}}
function levelNum(){try{return state?.selectedLevel||1}catch{return 1}}
function theme(){return themes[worldName()]||themes['Dino Frontier']}
function rgb(hex,a=1){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16},${(n>>8)&255},${n&255},${a})`}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function makeEngine(){const stage=$('#gameStage');if(!stage||!$('#worldModal.open'))return;if(engine?.root?.isConnected&&engine.world===worldName()&&engine.level===levelNum())return;destroy();
 const root=document.createElement('div');root.className='jkGameWorld';root.innerHTML=`<canvas class="jkGameCanvas" aria-label="Playable ${worldName()} world"></canvas><div class="jkGameHud"><span class="jkHudPill jkObjective"></span><button class="jkHudPill jkMissionToggle" type="button">🎯 Mission</button></div><div class="jkMovePad" aria-label="Movement controls"><button data-dir="up">▲</button><button data-dir="left">◀</button><button data-dir="down">▼</button><button data-dir="right">▶</button></div><div class="jkToastGame"></div>`;stage.prepend(root);
 const quest=document.createElement('div');quest.className='jkQuest';const mission=[...stage.children].find(n=>n!==root&&!n.classList.contains('worldAmbience')&&!n.classList.contains('adventureViewport')&&!n.classList.contains('nav3dPanel'));if(mission)quest.appendChild(mission);stage.appendChild(quest);
 engine={root,canvas:$('.jkGameCanvas',root),ctx:null,quest,world:worldName(),level:levelNum(),x:480,y:720,vx:0,vy:0,target:null,t:0,collected:new Set(),goalReady:false,npcs:[],particles:[],collects:[]};engine.ctx=engine.canvas.getContext('2d');
 const seed=[...engine.world].reduce((a,c)=>a+c.charCodeAt(0),0)+engine.level*97;for(let i=0;i<5;i++)engine.collects.push({x:280+((seed*(i+3)*17)%1350),y:280+((seed*(i+7)*29)%650),phase:i});for(let i=0;i<8;i++)engine.npcs.push({x:180+((seed*(i+5)*31)%1600),y:260+((seed*(i+9)*43)%700),phase:i*1.3,symbol:theme().npcs[i%theme().npcs.length]});
 root.querySelector('.jkObjective').textContent=`Collect 5 ${theme().collect} • Level ${engine.level}`;root.querySelector('.jkMissionToggle').onclick=()=>quest.classList.toggle('is-hidden');root.querySelectorAll('[data-dir]').forEach(b=>{const dir=b.dataset.dir;let timer;const step=()=>move(dir,18);b.onpointerdown=e=>{e.preventDefault();step();timer=setInterval(step,55)};b.onpointerup=b.onpointerleave=()=>clearInterval(timer)});
 engine.canvas.addEventListener('pointerdown',e=>{const r=engine.canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,cam=camera();engine.target={x:sx+cam.x,y:sy+cam.y}});resize();drawLoop();}
function destroy(){if(!engine)return;cancelAnimationFrame(engine.raf);engine.quest?.remove();engine.root?.remove();engine=null}
function resize(){if(!engine)return;const d=Math.min(devicePixelRatio||1,2),r=engine.root.getBoundingClientRect();engine.canvas.width=Math.max(1,Math.floor(r.width*d));engine.canvas.height=Math.max(1,Math.floor(r.height*d));engine.canvas.style.width=r.width+'px';engine.canvas.style.height=r.height+'px';engine.dpr=d}
function camera(){if(!engine)return{x:0,y:0,w:0,h:0};const w=engine.canvas.width/engine.dpr,h=engine.canvas.height/engine.dpr;return{x:Math.max(0,Math.min(2000-w,engine.x-w/2)),y:Math.max(0,Math.min(1200-h,engine.y-h/2)),w,h}}
function move(dir,n=14){if(!engine)return;if(dir==='left')engine.x-=n;if(dir==='right')engine.x+=n;if(dir==='up')engine.y-=n;if(dir==='down')engine.y+=n;engine.x=Math.max(60,Math.min(1940,engine.x));engine.y=Math.max(120,Math.min(1120,engine.y));engine.target=null;checkCollect()}
function toast(text){if(!engine)return;const t=$('.jkToastGame',engine.root);t.textContent=text;t.classList.remove('show');void t.offsetWidth;t.classList.add('show')}
function checkCollect(){if(!engine)return;engine.collects.forEach((c,i)=>{if(engine.collected.has(i))return;if(Math.hypot(engine.x-c.x,engine.y-c.y)<70){engine.collected.add(i);for(let n=0;n<14;n++)engine.particles.push({x:c.x,y:c.y,vx:(Math.random()-.5)*7,vy:(Math.random()-.9)*7,life:1});toast(`${theme().collect} found! ${engine.collected.size}/5`);$('.jkObjective',engine.root).textContent=engine.collected.size<5?`Collect 5 ${theme().collect} • ${engine.collected.size}/5`:`All collected — reach ${theme().goal}!`;if(engine.collected.size===5)engine.goalReady=true}});if(engine.goalReady&&Math.hypot(engine.x-1780,engine.y-250)<95){engine.goalReady=false;toast('World route complete! ✨');window.JamKarArcade?.burst?.('🏆');window.dispatchEvent(new CustomEvent('jamkar:adventurebonus',{detail:{world:engine.world,level:engine.level,profile:state.activeProfile}}))}}
function drawAvatar(ctx,x,y,t){ctx.save();ctx.translate(x,y);const bob=Math.sin(t*8)*3;ctx.translate(0,bob);ctx.fillStyle='rgba(16,45,70,.18)';ctx.beginPath();ctx.ellipse(0,33,28,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#243b63';roundRect(ctx,-19,-3,38,46,14);ctx.fill();ctx.fillStyle='#38c48d';roundRect(ctx,-17,0,34,32,12);ctx.fill();ctx.fillStyle='#f4b183';ctx.beginPath();ctx.arc(0,-15,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2d2d3a';ctx.beginPath();ctx.arc(0,-19,18,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#18243b';ctx.beginPath();ctx.arc(-6,-15,2,0,Math.PI*2);ctx.arc(6,-15,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#7a3e2d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-10,6,.2,Math.PI-.2);ctx.stroke();ctx.restore()}
function drawLoop(){if(!engine?.root?.isConnected)return;const e=engine,ctx=e.ctx,t=performance.now()/1000;e.t=t;const d=e.dpr||1,c=camera();ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,c.w,c.h);const th=theme();let g=ctx.createLinearGradient(0,0,0,c.h);g.addColorStop(0,th.sky[0]);g.addColorStop(1,th.sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,c.w,c.h);
 ctx.save();ctx.translate(-c.x,-c.y);ctx.fillStyle=th.ground;ctx.fillRect(0,610,2000,590);for(let i=0;i<22;i++){const x=(i*137)%1980,y=650+((i*97)%470);ctx.fillStyle=rgb(th.accent,.22);ctx.beginPath();ctx.arc(x,y,35+(i%4)*12,0,Math.PI*2);ctx.fill()}for(let i=0;i<18;i++){const x=90+i*110;ctx.fillStyle=rgb('#ffffff',.12);ctx.fillRect(x,610,2,590)}
 ctx.font='52px system-ui';ctx.textAlign='center';theme().props.forEach((p,j)=>{for(let i=0;i<4;i++){const x=150+j*430+i*80,y=540+((j+i)%3)*150;ctx.globalAlpha=.8;ctx.fillText(p,x,y)}});ctx.globalAlpha=1;
 e.npcs.forEach((n,i)=>{const xx=n.x+Math.sin(t*.7+n.phase)*42,yy=n.y+Math.cos(t*.9+n.phase)*14;ctx.font='58px system-ui';ctx.fillText(n.symbol,xx,yy)});
 e.collects.forEach((o,i)=>{if(e.collected.has(i))return;const yy=o.y+Math.sin(t*2+o.phase)*8;ctx.beginPath();ctx.fillStyle='rgba(255,255,255,.82)';ctx.arc(o.x,yy-14,32+Math.sin(t*3+i)*3,0,Math.PI*2);ctx.fill();ctx.font='31px system-ui';ctx.fillText(th.collect,o.x,yy-3)});
 ctx.font='74px system-ui';ctx.fillText(th.goal,1780,250+Math.sin(t*2)*8);if(e.goalReady){ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(1780,225,62+Math.sin(t*4)*7,0,Math.PI*2);ctx.stroke()}
 drawAvatar(ctx,e.x,e.y,t);e.particles=e.particles.filter(p=>p.life>0);e.particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.16;p.life-=.025;ctx.globalAlpha=p.life;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;ctx.restore();
 if(e.target){const dx=e.target.x-e.x,dy=e.target.y-e.y,dist=Math.hypot(dx,dy);if(dist>8){e.x+=dx/dist*5;e.y+=dy/dist*5;checkCollect()}else e.target=null}
 let dx=0,dy=0;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(dx||dy){e.x=Math.max(60,Math.min(1940,e.x+dx*5));e.y=Math.max(120,Math.min(1120,e.y+dy*5));checkCollect()}e.raf=requestAnimationFrame(drawLoop)}
function smoothNavigation(){const content=$('.content'),hero=$('.hero'),stats=$('.stats'),heads=$$('.sectionHead'),worlds=$('#worlds'),timeline=$('.timeline'),footer=$('.footer'),top=$$('.top .nav button'),side=$$('.sideNav button');function flash(){content?.classList.remove('jk-switching');void content?.offsetWidth;content?.classList.add('jk-switching')}function home(){[hero,stats,...heads,worlds,timeline,footer].forEach(x=>x&&(x.hidden=false));scrollTo({top:0,behavior:'smooth'});flash();sync(0)}function games(){hero&&(hero.hidden=true);stats&&(stats.hidden=true);heads.forEach((h,i)=>h.hidden=i!==0);worlds&&(worlds.hidden=false);timeline&&(timeline.hidden=true);footer&&(footer.hidden=false);scrollTo({top:0,behavior:'smooth'});flash();sync(1)}function sync(i){side.forEach(x=>x.classList.remove('active'));if(side[i])side[i].classList.add('active');top.forEach(x=>x.classList.remove('is-active'));if(i===1&&top[0])top[0].classList.add('is-active')}
 if(side[0])side[0].onclick=home;if(side[1])side[1].onclick=games;if(top[0])top[0].onclick=games;if(top[1])top[1].onclick=()=>{const w=(typeof worlds!=='undefined'?window.worlds:[]);const t=(typeof window.openWorld==='function');if(t)openWorld('Time Builder')};if(top[2])top[2].onclick=()=>window.JamKarDashboard?.open?.();if(side[2])side[2].onclick=()=>openWorld('Time Builder');if(side[3])side[3].onclick=()=>window.JamKarDashboard?.open?.();if(side[4])side[4].onclick=()=>openAccount('join');window.JamKarViews={home,games}}
function ensureBack(){const head=$('#worldModal .modalHead');if(!head)return;let b=$('#backWorld');if(!b){b=document.createElement('button');b.id='backWorld';b.className='worldBack';b.innerHTML='← <span>Worlds</span>';head.prepend(b)}b.onclick=()=>{if($('#worldModal.open')){if(typeof closeWorld==='function')closeWorld();else $('#worldModal')?.classList.remove('open')}window.JamKarViews?.games?.()}}
addEventListener('keydown',e=>{if(!$('#worldModal.open')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){keys.add(k);e.preventDefault()}if(k==='escape'){if(typeof closeWorld==='function')closeWorld();window.JamKarViews?.games?.()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('resize',resize);
function init(){smoothNavigation();ensureBack();const stage=$('#gameStage');if(stage)new MutationObserver(()=>{clearTimeout(window.__jkV2Mount);window.__jkV2Mount=setTimeout(makeEngine,35)}).observe(stage,{childList:true,subtree:false});const modal=$('#worldModal');if(modal)new MutationObserver(()=>{ensureBack();if(modal.classList.contains('open'))setTimeout(makeEngine,20);else destroy()}).observe(modal,{attributes:true,attributeFilter:['class']})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();