(()=>{
const previousStartLevel=startLevel;
function finishFree(message){const key=state.activeProfile+'|'+state.selected.name;const n=state.selectedLevel;if(n>=30){state.progress[key]=30;save();renderStats();renderWorlds();renderLevels();els.stage.innerHTML=`<div class="victory"><div class="victoryIcon">🏆</div><h3>${state.selected.name} complete!</h3><p>${state.activeProfile} completed all 30 levels.</p><button class="primary" id="closeWin">Choose another world</button></div>`;document.querySelector('#closeWin').onclick=()=>els.modal.classList.remove('open');return}state.progress[key]=Math.max(progressFor(state.selected.name),n+1);save();renderStats();renderWorlds();renderLevels();const fb=document.querySelector('#feedback');if(fb)fb.textContent=message;setTimeout(()=>{if(!state.paid&&n===3){els.modal.classList.remove('open');openAccount('unlock')}else startLevel(n+1)},650)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}

function dinoDig(n){const fossils=Math.min(5,2+Math.floor(n/8));const cells=12;const spots=new Set(shuffle(Array.from({length:cells},(_,i)=>i)).slice(0,fossils));let found=0,turns=0;els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Fossil Dig · Level ${n}</div><h3>Excavate the fossil site</h3><p class="gameHint">Tap soil squares to uncover hidden fossils. Find all ${fossils} fossils.</p><div class="digGrid">${Array.from({length:cells},(_,i)=>`<button class="digCell" data-dig="${i}">🟫</button>`).join('')}</div><p class="note" id="feedback">Fossils: 0 / ${fossils}</p></div>`;document.querySelectorAll('[data-dig]').forEach(c=>c.onclick=()=>{if(c.disabled)return;c.disabled=true;turns++;const hit=spots.has(Number(c.dataset.dig));c.textContent=hit?'🦴':'🪨';c.classList.add(hit?'hit':'miss');if(hit)found++;document.querySelector('#feedback').textContent=`Fossils: ${found} / ${fossils} · Digs: ${turns}`;if(found===fossils)setTimeout(()=>finishFree('Excavation complete! 🦖'),350)})}

function oceanDive(n){const creatures=['🐠','🐟','🐙','🦀','🐬','🦈','🐢','🪼'];const target=Math.min(6,3+Math.floor(n/7));let oxygen=10+Math.floor(n/3),seen=0;els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Ocean Dive · Level ${n}</div><h3>Explore before oxygen runs low</h3><div class="resourceBar"><span class="resourcePill" id="oxygen">🫧 Oxygen: ${oxygen}</span><span class="resourcePill">🔎 Discoveries: <b id="seen">0</b> / ${target}</span></div><div class="oceanZone" id="oceanZone"></div><p class="note" id="feedback">Tap sea creatures to record discoveries.</p></div>`;const zone=document.querySelector('#oceanZone');function spawn(){if(seen>=target)return;zone.innerHTML='';const b=document.createElement('button');b.className='seaCreature';b.textContent=creatures[Math.floor(Math.random()*creatures.length)];b.style.left=Math.floor(Math.random()*80+5)+'%';b.style.top=Math.floor(Math.random()*65+10)+'%';b.onclick=()=>{seen++;oxygen=Math.max(0,oxygen-1);document.querySelector('#seen').textContent=seen;document.querySelector('#oxygen').textContent='🫧 Oxygen: '+oxygen;if(seen>=target)finishFree('Dive complete — amazing discoveries! 🐋');else spawn()};zone.appendChild(b)}spawn()}

function ancientOrder(n){const eras=n<11?['Stone tools','Farming','Ancient cities','Writing']:n<21?['Old Kingdom','Middle Kingdom','New Kingdom','Roman Egypt']:['Early settlement','Bronze Age','Classical era','Medieval era','Modern era'];const shuffled=shuffle(eras);let picked=[];els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Timeline · Level ${n}</div><h3>Put history in order</h3><p class="gameHint">Tap each event from earliest to latest.</p><div class="commandTrack" id="historyTrack"><span class="note">Your timeline appears here</span></div><div class="commandBank">${shuffled.map((x,i)=>`<button class="commandBtn" data-history="${i}" data-label="${x}">${x}</button>`).join('')}</div><div class="gameActions"><button class="secondary" id="resetHistory">Reset</button><button class="primary" id="checkHistory">Check timeline</button></div><p class="note" id="feedback">Build the timeline.</p></div>`;const render=()=>document.querySelector('#historyTrack').innerHTML=picked.length?picked.map(x=>`<span class="commandToken">${x}</span>`).join(''):'<span class="note">Your timeline appears here</span>';document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{picked.push(b.dataset.label);b.classList.add('used');render()});document.querySelector('#resetHistory').onclick=()=>{picked=[];document.querySelectorAll('[data-history]').forEach(b=>b.classList.remove('used'));render()};document.querySelector('#checkHistory').onclick=()=>{if(picked.join('|')===eras.join('|'))finishFree('Timeline complete! 🏺');else document.querySelector('#feedback').textContent='Check the order and try again.'}}

function habitatMatch(n){const pairs=[['🦁','Savannah'],['🐻‍❄️','Arctic'],['🐫','Desert'],['🐸','Wetland'],['🐒','Rainforest'],['🐧','Polar coast']];const count=Math.min(6,3+Math.floor(n/7));const round=shuffle(pairs).slice(0,count);let index=0,correct=0;function draw(){if(index>=round.length){finishFree('Every animal found its habitat! 🦁');return}const [animal,home]=round[index];const choices=shuffle([home,...pairs.map(p=>p[1]).filter(x=>x!==home).slice(0,3)]);els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Habitat Match · Level ${n}</div><h3>Where does ${animal} belong?</h3><p class="gameHint">Match each animal to its natural habitat.</p><div class="habitatAnimal">${animal}</div><div class="choices">${choices.map(x=>`<button class="choice" data-home="${x}">${x}</button>`).join('')}</div><p class="note" id="feedback">Animal ${index+1} / ${round.length}</p></div>`;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{if(b.dataset.home===home){b.classList.add('correct');correct++;index++;setTimeout(draw,350)}else{b.classList.add('wrong');document.querySelector('#feedback').textContent='Try another habitat.';setTimeout(()=>b.classList.remove('wrong'),400)}})}draw()}

function spaceNav(n){const route=n<11?['🌍','🌙','🔴']:n<21?['🌍','🔴','🪐','⭐']:['🌍','🌙','🔴','🪐','☄️','⭐'];let step=0;els.stage.innerHTML=`<div class="miniGame"><div class="eyebrow">Space Mission · Level ${n}</div><h3>Navigate the mission route</h3><p class="gameHint">Follow the route in order: ${route.join(' → ')}</p><div class="spaceMap">${shuffle(route).map((x,i)=>`<button class="spaceNode" data-space="${x}">${x}</button>`).join('')}</div><p class="note" id="feedback">Next destination: ${route[0]}</p></div>`;document.querySelectorAll('[data-space]').forEach(b=>b.onclick=()=>{if(b.dataset.space===route[step]){b.classList.add('visited');b.disabled=true;step++;if(step===route.length)finishFree('Mission route complete! 🚀');else document.querySelector('#feedback').textContent='Next destination: '+route[step]}else{b.classList.add('wrong');document.querySelector('#feedback').textContent='That is not the next stop. Follow the route.';setTimeout(()=>b.classList.remove('wrong'),450)}})}

startLevel=function(n){state.selectedLevel=n;switch(state.selected.name){case'Dino Frontier':dinoDig(n);break;case'Deep Ocean':oceanDive(n);break;case'Ancient Worlds':ancientOrder(n);break;case'Wild Planet':habitatMatch(n);break;case'Deep Space':spaceNav(n);break;default:previousStartLevel(n)}};
})();