(()=>{
const additions=[
{name:'Music Makers',emoji:'🎵',cat:'Creative',cls:'c7',free:false,desc:'Rhythm, patterns, instruments and musical memory challenges.'},
{name:'Art Studio',emoji:'🎨',cat:'Creative',cls:'c6',free:false,desc:'Colour, shape, design and visual creativity missions.'},
{name:'Weather Watch',emoji:'🌦️',cat:'Science',cls:'c2',free:false,desc:'Clouds, seasons, forecasts and climate observation challenges.'},
{name:'Engineering Bay',emoji:'🛠️',cat:'Logic',cls:'c8',free:false,desc:'Build bridges, choose materials and solve practical engineering puzzles.'},
{name:'Language Lab',emoji:'🗣️',cat:'English',cls:'c5',free:false,desc:'Words, meanings, sentence building and communication challenges.'},
{name:'Mystery Maze',emoji:'🕵️',cat:'Puzzles',cls:'c3',free:false,desc:'Clues, deduction, codes and safe mystery-solving adventures.'},
{name:'Garden Guardians',emoji:'🌱',cat:'Nature',cls:'c4',free:false,desc:'Grow habitats, learn plant life cycles and protect pollinators.'},
{name:'Robot Factory',emoji:'⚙️',cat:'Logic',cls:'c1',free:false,desc:'Assemble friendly robots using sequences, parts and logic.'}
];
additions.forEach(w=>{if(!worlds.some(x=>x.name===w.name))worlds.push(w)});renderStats();renderWorlds();
const priorStart=startLevel;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function finish(message='Mission complete! ✨'){
 const n=state.selectedLevel,key=state.activeProfile+'|'+state.selected.name;
 if(n>=30){state.progress[key]=30;save();renderStats();renderWorlds();renderLevels();els.stage.innerHTML=`<div class="victory"><div class="victoryIcon">🏆</div><h3>${state.selected.name} complete!</h3><p>${state.activeProfile} completed all 30 levels.</p><button class="primary" id="newWorldClose">Choose another world</button></div>`;document.querySelector('#newWorldClose').onclick=()=>els.modal.classList.remove('open');return}
 state.progress[key]=Math.max(progressFor(state.selected.name),n+1);save();renderStats();renderWorlds();renderLevels();const fb=document.querySelector('#feedback');if(fb)fb.textContent=message;setTimeout(()=>startLevel(n+1),550)
}
function choices(title,icon,q,correct,wrong,hint){const all=shuffle([correct,...wrong.slice(0,3)]);els.stage.innerHTML=`<div class="miniGame missionGame"><div class="missionCharacter" aria-hidden="true">${icon}</div><div class="eyebrow">${title} · Level ${state.selectedLevel}</div><p class="question">${q}</p><div class="choices">${all.map(x=>`<button class="choice" data-extra="${x===correct?'1':'0'}">${x}</button>`).join('')}</div><p class="note" id="feedback">${hint}</p></div>`;document.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-extra]').forEach(x=>x.disabled=true);if(b.dataset.extra==='1'){b.classList.add('correct');setTimeout(()=>finish(),300)}else{b.classList.add('wrong');document.querySelector('[data-extra="1"]')?.classList.add('correct');document.querySelector('#feedback').textContent='Good try — check the highlighted answer.';setTimeout(()=>{document.querySelectorAll('[data-extra]').forEach(x=>{x.disabled=false;x.classList.remove('wrong','correct')})},850)}})}
function music(){const n=state.selectedLevel;const seq=['🥁','🎹','🎸','🎺'].slice(0,Math.min(4,2+Math.floor(n/10)));const target=Array.from({length:Math.min(7,3+Math.floor(n/6))},()=>seq[Math.floor(Math.random()*seq.length)]);let i=0;els.stage.innerHTML=`<div class="miniGame"><div class="missionCharacter">🎵</div><div class="eyebrow">Music Makers · Level ${n}</div><h3>Repeat the rhythm</h3><p class="gameHint">Remember this pattern: <b>${target.join(' ')}</b></p><div class="commandBank">${seq.map(x=>`<button class="commandBtn" data-note="${x}">${x}</button>`).join('')}</div><p class="note" id="feedback">Beat 1 of ${target.length}</p></div>`;document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>{if(b.dataset.note===target[i]){i++;if(i===target.length)finish('Perfect rhythm! 🎶');else document.querySelector('#feedback').textContent=`Beat ${i+1} of ${target.length}`}else{i=0;document.querySelector('#feedback').textContent='Try the rhythm again from the start.'}})}
function art(){const bank=[['Red and yellow mix to make…','Orange',['Green','Purple','Blue']],['Which shape has four equal sides?','Square',['Triangle','Circle','Oval']],['Which pair are warm colours?','Red and orange',['Blue and green','Purple and blue','Grey and black']],['A repeating visual design is called a…','Pattern',['Battery','Orbit','Engine']],['Which tool is commonly used for painting?','Brush',['Compass only','Hammer','Spanner']]];const x=bank[(state.selectedLevel-1)%bank.length];choices('Art Studio','🎨',x[0],x[1],x[2],'Think about colour, shape and design.')}
function weather(){const bank=[['Dark clouds and thunder usually suggest…','A storm',['A heatwave only','Clear skies','No weather']],['A thermometer measures…','Temperature',['Wind direction','Distance','Time']],['Rain, snow and hail are forms of…','Precipitation',['Electricity','Gravity','Soil']],['Which instrument shows wind direction?','Weather vane',['Ruler','Microscope','Clock']],['Summer days are usually…','Warmer',['Always snowy','Always dark','Always freezing']]];const x=bank[(state.selectedLevel-1)%bank.length];choices('Weather Watch','🌦️',x[0],x[1],x[2],'Observe weather clues like a young forecaster.')}
function engineering(){const bank=[['A bridge needs a strong base called a…','Foundation',['Cloud','Battery','Compass']],['Which material is usually strongest for a toy bridge?','Wooden beams',['Tissue paper','Cotton wool','Leaves']],['A triangle is useful in structures because it is…','Rigid',['Liquid','Invisible','Magnetic']],['What helps a wheel turn around its centre?','Axle',['Roof','Window','Sail']],['Before building, engineers usually…','Plan and test',['Guess once','Ignore safety','Skip measurements']]];const x=bank[(state.selectedLevel-1)%bank.length];choices('Engineering Bay','🛠️',x[0],x[1],x[2],'Plan, test and choose the safest solution.')}
function language(){const bank=[['Choose the polite request.','Could you please help me?',['Help now!','Move!','Give it!']],['Which word means “very large”?','Huge',['Tiny','Slow','Quiet']],['Complete: “We ___ to the museum yesterday.”','went',['go','goed','going']],['Which sentence is a question?','Where are we going?',['We are going home.','What a lovely day!','Please sit down.']],['Choose the best greeting in the morning.','Good morning',['Good night','Goodbye forever','Sleep well']]];const x=bank[(state.selectedLevel-1)%bank.length];choices('Language Lab','🗣️',x[0],x[1],x[2],'Choose clear, kind and correct language.')}
function mystery(){const n=state.selectedLevel;const a=2+(n%7),b=a+2,c=b+2;choices('Mystery Maze','🕵️',`Clue: ${a}, ${b}, ${c}. What number comes next?`,String(c+2),[String(c+1),String(c+3),String(a)],'Use the clues and find the pattern.')}
function garden(){const bank=[['Which part of a plant usually grows underground?','Roots',['Flower','Fruit','Leaf']],['Bees help many plants by…','Pollinating flowers',['Turning soil to metal','Freezing seeds','Removing sunlight']],['Plants need water, light and…','Nutrients',['Plastic','Smoke','Coins']],['Which creature is a useful garden pollinator?','Bee',['Toy robot','Car','Submarine']],['Compost can help improve…','Soil',['Wi-Fi','Moonlight','Traffic']]];const x=bank[(state.selectedLevel-1)%bank.length];choices('Garden Guardians','🌱',x[0],x[1],x[2],'Help the garden grow and protect living things.')}
function robot(){const n=state.selectedLevel;const parts=['🔋','⚙️','🦾','👁️'];const target=parts.slice(0,Math.min(4,2+Math.floor(n/10)));let picked=[];els.stage.innerHTML=`<div class="miniGame"><div class="missionCharacter">🤖</div><div class="eyebrow">Robot Factory · Level ${n}</div><h3>Assemble the helper robot</h3><p class="gameHint">Install parts in this order: ${target.join(' → ')}</p><div class="commandBank">${shuffle(target).map(x=>`<button class="commandBtn" data-part="${x}">${x}</button>`).join('')}</div><p class="note" id="feedback">Choose part 1 of ${target.length}</p></div>`;document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{if(b.dataset.part===target[picked.length]){picked.push(b.dataset.part);b.disabled=true;b.classList.add('used');if(picked.length===target.length)finish('Robot assembled! 🤖');else document.querySelector('#feedback').textContent=`Choose part ${picked.length+1} of ${target.length}`}else document.querySelector('#feedback').textContent='That part goes later. Check the sequence.'})}
startLevel=function(n){state.selectedLevel=n;switch(state.selected?.name){case'Music Makers':music();break;case'Art Studio':art();break;case'Weather Watch':weather();break;case'Engineering Bay':engineering();break;case'Language Lab':language();break;case'Mystery Maze':mystery();break;case'Garden Guardians':garden();break;case'Robot Factory':robot();break;default:priorStart(n)}};
})();