(()=>{
const backend=window.JamKarBackend;if(!backend)return;
const priorStart=startLevel;
const eras=[
 {key:'prehistoric',name:'Prehistoric Camp',icon:'🔥',unlock:1,items:[['⛺','Shelter'],['🔥','Fire'],['💧','Water'],['🪵','Wood']]},
 {key:'settlement',name:'Early Settlement',icon:'🌾',unlock:5,items:[['🏠','Home'],['🌾','Farm'],['🐑','Livestock'],['🛖','Workshop']]},
 {key:'ancient',name:'Ancient City',icon:'🏛️',unlock:10,items:[['🏛️','Temple'],['🏺','Market'],['🧱','Wall'],['⛲','Fountain']]},
 {key:'industrial',name:'Industrial Age',icon:'⚙️',unlock:15,items:[['🏭','Factory'],['🚂','Rail'],['⚙️','Workshop'],['🌉','Bridge']]},
 {key:'modern',name:'Modern World',icon:'🏙️',unlock:20,items:[['🏫','School'],['🏥','Hospital'],['🏢','Tower'],['🚇','Transit']]},
 {key:'future',name:'Future Colony',icon:'🚀',unlock:25,items:[['🤖','Robotics'],['☀️','Solar'],['🛸','Skyport'],['🌌','Space Lab']]}
];
let build={era:'prehistoric',layout:[],resources:20};let childId=null;let saving=false;let saveQueued=false;
async function resolveChild(){if(!backend.state.user)return null;const family=await backend.getFamily();const child=family?.children?.find(c=>c.username===state.activeProfile)||family?.children?.[0];childId=child?.id||null;return child||null}
function unlockedEra(level){let found=eras[0];for(const e of eras)if(level>=e.unlock)found=e;return found}
function normaliseLayout(v){return Array.isArray(v)?v.filter(x=>x&&Number.isInteger(x.cell)&&x.cell>=0&&x.cell<36&&typeof x.icon==='string').slice(0,36):[]}
async function loadBuild(){const child=await resolveChild();if(!child)return;const remote=await backend.loadWorldBuild(child.id);if(remote){build={era:remote.era||'prehistoric',layout:normaliseLayout(remote.layout),resources:Number(remote.resources??20)}}else{const key='jamkar_build_'+state.activeProfile;try{const local=JSON.parse(localStorage.getItem(key)||'null');if(local)build={era:local.era||'prehistoric',layout:normaliseLayout(local.layout),resources:Number(local.resources??20)}}catch{}}}
async function flushSave(){if(!childId||saving)return;saving=true;do{saveQueued=false;const snap={era:build.era,layout:build.layout.map(x=>({...x})),resources:build.resources};try{await backend.saveWorldBuild(childId,snap.era,snap.layout,snap.resources)}catch(err){console.error('World save failed',err)}}while(saveQueued);saving=false}
function persist(){const key='jamkar_build_'+state.activeProfile;localStorage.setItem(key,JSON.stringify(build));if(!childId)return Promise.resolve();if(saving){saveQueued=true;return Promise.resolve()}return flushSave()}
function levelNow(){return Math.max(1,progressFor('Time Builder'))}
function renderBuilder(){const maxEra=unlockedEra(levelNow());const current=eras.find(e=>e.key===build.era)||eras[0];if(current.unlock>levelNow())build.era=maxEra.key;const era=eras.find(e=>e.key===build.era)||eras[0];let selected=era.items[0];
 els.stage.innerHTML=`<div class="persistentBuilder"><div class="eyebrow">Persistent World · Level ${state.selectedLevel}</div><div class="builderHero"><div><h3>${era.icon} ${era.name}</h3><p class="gameHint">Build one civilisation that grows from prehistory to the future. Your map saves to this child profile.</p></div><div class="resourcePill">⚙️ Resources: <b id="persistResources">${build.resources}</b></div></div><div class="eraTabs">${eras.map(e=>`<button class="eraTab ${e.key===era.key?'active':''}" data-era="${e.key}" ${e.unlock>levelNow()?'disabled':''}>${e.icon}<span>${e.name}</span><small>${e.unlock>levelNow()?'Unlock L'+e.unlock:'Open'}</small></button>`).join('')}</div><div class="persistentBuilderWrap"><div class="persistentGrid" id="persistentGrid">${Array.from({length:36},(_,i)=>{const x=build.layout.find(v=>v.cell===i);return `<button class="persistentCell ${x?'filled':''}" data-cell="${i}" aria-label="World tile ${i+1}">${x?x.icon:''}</button>`}).join('')}</div><div class="persistentPalette"><h4>Build pieces</h4>${era.items.map((it,i)=>`<button class="buildTile ${i===0?'active':''}" data-piece="${i}">${it[0]} ${it[1]}</button>`).join('')}<button class="secondary" id="clearBuild">Clear selected tile</button><p class="note" id="builderStatus">Tap a piece, then tap the map. Each placement costs 1 resource.</p></div></div><div class="gameActions"><button class="secondary" id="earnResource">Complete learning challenge +5 resources</button><button class="primary" id="finishBuilderLevel">Finish this level</button></div></div>`;
 document.querySelectorAll('[data-piece]').forEach((b,i)=>b.onclick=()=>{selected=era.items[i];document.querySelectorAll('[data-piece]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
 let erase=false;document.querySelector('#clearBuild').onclick=()=>{erase=!erase;document.querySelector('#clearBuild').classList.toggle('active',erase);document.querySelector('#builderStatus').textContent=erase?'Erase mode: tap a placed tile to remove it.':'Build mode: choose a piece and place it on the map.'};
 document.querySelectorAll('[data-cell]').forEach(cell=>cell.onclick=()=>{const n=Number(cell.dataset.cell),existing=build.layout.findIndex(x=>x.cell===n);if(erase){if(existing>=0){build.layout.splice(existing,1);cell.textContent='';cell.classList.remove('filled');build.resources++;document.querySelector('#persistResources').textContent=build.resources;persist()}return}if(existing>=0){document.querySelector('#builderStatus').textContent='That tile is occupied. Use erase mode first.';return}if(build.resources<1){document.querySelector('#builderStatus').textContent='You need more resources. Complete the learning challenge.';return}build.layout.push({cell:n,icon:selected[0],name:selected[1],era:era.key});build.resources--;cell.textContent=selected[0];cell.classList.add('filled');document.querySelector('#persistResources').textContent=build.resources;document.querySelector('#builderStatus').textContent=`Built ${selected[1]} — save queued.`;persist()});
 document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{if(b.disabled)return;build.era=b.dataset.era;persist();renderBuilder()});
 document.querySelector('#earnResource').onclick=()=>{const a=2+(state.selectedLevel%8),b=3+(state.selectedLevel%6),ans=a+b;const guesses=[ans,ans+1,Math.max(0,ans-1),ans+3].sort(()=>Math.random()-.5);els.stage.querySelector('#builderStatus').innerHTML=`Resource challenge: What is ${a} + ${b}? <span id="resourceChoices"></span>`;const box=document.querySelector('#resourceChoices');guesses.forEach(g=>{const bt=document.createElement('button');bt.className='choice miniResource';bt.textContent=g;bt.onclick=()=>{if(g===ans){build.resources+=5;document.querySelector('#persistResources').textContent=build.resources;document.querySelector('#builderStatus').textContent='Great work! +5 resources added.';persist()}else document.querySelector('#builderStatus').textContent='Try again — check your addition.'};box.appendChild(bt)})};
 document.querySelector('#finishBuilderLevel').onclick=()=>{if(build.layout.length<Math.min(3+Math.floor(state.selectedLevel/5),12)){document.querySelector('#builderStatus').textContent='Add a few more buildings before finishing this level.';return}const key=state.activeProfile+'|Time Builder';state.progress[key]=Math.max(progressFor('Time Builder'),Math.min(30,state.selectedLevel+1));save();persist();renderStats();renderWorlds();renderLevels();toast('Civilisation saved! Next level unlocked.');setTimeout(()=>{if(state.selectedLevel<30)startLevel(state.selectedLevel+1)},550)};
}
async function openPersistent(n){state.selectedLevel=n;els.stage.innerHTML='<div class="miniGame"><div class="question">Loading your civilisation…</div></div>';try{await loadBuild();renderBuilder()}catch(err){console.error(err);els.stage.innerHTML='<div class="miniGame"><p class="question">Could not load your saved world.</p><p class="note">Please check the connection and try again.</p></div>'}}
startLevel=function(n){if(state.selected?.name==='Time Builder'){openPersistent(n);return}priorStart(n)};
window.addEventListener('jamkar:auth',()=>{childId=null});window.addEventListener('jamkar:family',()=>{childId=null});
})();