(()=>{
const backend=window.JamKarBackend;if(!backend)return;const priorStart=startLevel;
const eras=[
 {key:'prehistoric',name:'Prehistoric Camp',icon:'🔥',unlock:1,items:[['⛺','Shelter'],['🔥','Fire'],['💧','Water'],['🪵','Wood']]},
 {key:'settlement',name:'Early Settlement',icon:'🌾',unlock:5,items:[['🏠','Home'],['🌾','Farm'],['🐑','Livestock'],['🛖','Workshop']]},
 {key:'ancient',name:'Ancient City',icon:'🏛️',unlock:10,items:[['🏛️','Temple'],['🏺','Market'],['🧱','Wall'],['⛲','Fountain']]},
 {key:'industrial',name:'Industrial Age',icon:'⚙️',unlock:15,items:[['🏭','Factory'],['🚂','Rail'],['⚙️','Workshop'],['🌉','Bridge']]},
 {key:'modern',name:'Modern World',icon:'🏙️',unlock:20,items:[['🏫','School'],['🏥','Hospital'],['🏢','Tower'],['🚇','Transit']]},
 {key:'future',name:'Future Colony',icon:'🚀',unlock:25,items:[['🤖','Robotics'],['☀️','Solar'],['🛸','Skyport'],['🌌','Space Lab']]}
];
let build={era:'prehistoric',layout:[],resources:20},childId=null,saving=false,saveQueued=false;
async function resolveChild(){if(!backend.state.user)return null;const family=await backend.getFamily(),child=family?.children?.find(c=>c.username===state.activeProfile)||family?.children?.[0];childId=child?.id||null;return child||null}
function unlockedEra(level){let found=eras[0];for(const e of eras)if(level>=e.unlock)found=e;return found}
function normaliseLayout(v){return Array.isArray(v)?v.filter(x=>x&&Number.isInteger(x.cell)&&x.cell>=0&&x.cell<36&&typeof x.icon==='string').slice(0,36):[]}
function localKey(){return 'jamkar_build_'+state.activeProfile}
async function loadBuild(){const child=await resolveChild();let local=null;try{local=JSON.parse(localStorage.getItem(localKey())||'null')}catch{}if(child){const remote=await backend.loadWorldBuild(child.id);if(remote)build={era:remote.era||'prehistoric',layout:normaliseLayout(remote.layout),resources:Number(remote.resources??20)};else if(local){build={era:local.era||'prehistoric',layout:normaliseLayout(local.layout),resources:Number(local.resources??20)};persist()}}else if(local)build={era:local.era||'prehistoric',layout:normaliseLayout(local.layout),resources:Number(local.resources??20)}
async function flushSave(){if(!childId||saving)return;saving=true;do{saveQueued=false;const snap={era:build.era,layout:build.layout.map(x=>({...x})),resources:build.resources};try{await backend.saveWorldBuild(childId,snap.era,snap.layout,snap.resources)}catch(err){console.error('World save failed',err)}}while(saveQueued);saving=false}
function persist(){localStorage.setItem(localKey(),JSON.stringify(build));if(!childId)return Promise.resolve();if(saving){saveQueued=true;return Promise.resolve()}return flushSave()}
function levelNow(){return Math.max(1,progressFor('Time Builder'))}
function civStats(){let population=0,food=0,water=0,knowledge=0,energy=0,mobility=0;for(const x of build.layout){const n=x.name||'';if(/Shelter|Home|Tower/.test(n))population+=2;if(/Farm|Livestock|Market/.test(n))food+=2;if(/Water|Fountain|Hospital/.test(n))water+=2;if(/Temple|School|Space Lab|Robotics/.test(n))knowledge+=2;if(/Fire|Factory|Solar|Robotics/.test(n))energy+=2;if(/Rail|Bridge|Transit|Skyport/.test(n))mobility+=2}return{population,food,water,knowledge,energy,mobility}}
function objective(){const n=state.selectedLevel;if(n<5)return{era:'prehistoric',need:['Shelter','Water'],text:'Create shelter and secure water.'};if(n<10)return{era:'settlement',need:['Home','Farm'],text:'Grow a settlement with homes and food.'};if(n<15)return{era:'ancient',need:['Temple','Market'],text:'Build a centre for culture and trade.'};if(n<20)return{era:'industrial',need:['Factory','Rail'],text:'Connect production with transport.'};if(n<25)return{era:'modern',need:['School','Hospital'],text:'Support people with education and health.'};return{era:'future',need:['Robotics','Solar'],text:'Power a future colony with clean technology.'}}
function hasObjective(o){return o.need.every(name=>build.layout.some(x=>x.name===name))}
function statsHtml(){const s=civStats();return `<div class="civilMeters"><span>👥 ${s.population}</span><span>🌾 ${s.food}</span><span>💧 ${s.water}</span><span>📚 ${s.knowledge}</span><span>⚡ ${s.energy}</span><span>🚇 ${s.mobility}</span></div>`}
function refreshStats(){const el=document.querySelector('#civilMetersWrap');if(el)el.innerHTML=statsHtml()}
function renderBuilder(){const maxEra=unlockedEra(levelNow()),current=eras.find(e=>e.key===build.era)||eras[0];if(current.unlock>levelNow())build.era=maxEra.key;const era=eras.find(e=>e.key===build.era)||eras[0],goal=objective();let selected=era.items[0],erase=false;
 els.stage.innerHTML=`<div class="persistentBuilder"><div class="eyebrow">Persistent World · Level ${state.selectedLevel}</div><div class="builderHero"><div><h3>${era.icon} ${era.name}</h3><p class="gameHint">Build one civilisation that grows from prehistory to the future. Your map, resources and upgrades persist for this child profile.</p></div><div class="resourcePill">⚙️ Resources: <b id="persistResources">${build.resources}</b></div></div><div id="civilMetersWrap">${statsHtml()}</div><div class="builderMission ${hasObjective(goal)?'complete':''}"><b>Era mission:</b> ${goal.text} <small>${hasObjective(goal)?'✓ Ready':'Required: '+goal.need.join(' + ')}</small></div><div class="eraTabs">${eras.map(e=>`<button class="eraTab ${e.key===era.key?'active':''}" data-era="${e.key}" ${e.unlock>levelNow()?'disabled':''}>${e.icon}<span>${e.name}</span><small>${e.unlock>levelNow()?'Unlock L'+e.unlock:'Open'}</small></button>`).join('')}</div><div class="persistentBuilderWrap"><div class="persistentGrid" id="persistentGrid">${Array.from({length:36},(_,i)=>{const x=build.layout.find(v=>v.cell===i);return `<button class="persistentCell ${x?'filled':''}" data-cell="${i}" aria-label="World tile ${i+1}">${x?`<span>${x.icon}</span><small>${x.name}</small>`:''}</button>`}).join('')}</div><div class="persistentPalette"><h4>Build pieces</h4>${era.items.map((it,i)=>`<button class="buildTile ${i===0?'active':''}" data-piece="${i}">${it[0]} ${it[1]}</button>`).join('')}<button class="secondary" id="clearBuild">Clear selected tile</button><p class="note" id="builderStatus">Choose a piece, then place it on the map. Each placement costs 1 resource.</p></div></div><div class="gameActions"><button class="secondary" id="earnResource">Learning challenge +5 resources</button><button class="primary" id="finishBuilderLevel">Complete era mission</button></div></div>`;
 document.querySelectorAll('[data-piece]').forEach((b,i)=>b.onclick=()=>{selected=era.items[i];document.querySelectorAll('[data-piece]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
 document.querySelector('#clearBuild').onclick=()=>{erase=!erase;document.querySelector('#clearBuild').classList.toggle('active',erase);document.querySelector('#builderStatus').textContent=erase?'Erase mode: tap a placed tile to remove it.':'Build mode: choose a piece and place it on the map.'};
 document.querySelectorAll('[data-cell]').forEach(cell=>cell.onclick=()=>{const n=Number(cell.dataset.cell),existing=build.layout.findIndex(x=>x.cell===n);if(erase){if(existing>=0){build.layout.splice(existing,1);build.resources++;persist();renderBuilder()}return}if(existing>=0){document.querySelector('#builderStatus').textContent='That tile is occupied. Use erase mode first.';return}if(build.resources<1){document.querySelector('#builderStatus').textContent='You need more resources. Complete the learning challenge.';return}build.layout.push({cell:n,icon:selected[0],name:selected[1],era:era.key});build.resources--;persist();renderBuilder()});
 document.querySelectorAll('[data-era]').forEach(b=>b.onclick=()=>{if(!b.disabled){build.era=b.dataset.era;persist();renderBuilder()}});
 document.querySelector('#earnResource').onclick=()=>{const a=2+(state.selectedLevel%8),b=3+(state.selectedLevel%6),ans=a+b,guesses=[ans,ans+1,Math.max(0,ans-1),ans+3].sort(()=>Math.random()-.5);const status=document.querySelector('#builderStatus');status.innerHTML=`Resource challenge: What is ${a} + ${b}? <span id="resourceChoices"></span>`;const box=document.querySelector('#resourceChoices');guesses.forEach(g=>{const bt=document.createElement('button');bt.className='choice miniResource';bt.textContent=g;bt.onclick=()=>{if(g===ans){build.resources+=5;persist();renderBuilder()}else status.textContent='Try again — check your addition.'};box.appendChild(bt)})};
 document.querySelector('#finishBuilderLevel').onclick=()=>{if(!hasObjective(goal)){document.querySelector('#builderStatus').textContent='Complete the era mission first: '+goal.need.join(' + ')+'.';return}const minimum=Math.min(4+Math.floor(state.selectedLevel/5),12);if(build.layout.length<minimum){document.querySelector('#builderStatus').textContent=`Grow your civilisation to at least ${minimum} buildings before finishing this level.`;return}const key=state.activeProfile+'|Time Builder';if(window.JamKarCompleteLevel){window.JamKarCompleteLevel('Civilisation mission complete! 🏗️');persist();return}state.progress[key]=Math.max(progressFor('Time Builder'),Math.min(30,state.selectedLevel+1));save();persist();renderStats();renderWorlds();renderLevels();toast('Civilisation saved! Next level unlocked.');if(state.selectedLevel<30)setTimeout(()=>startLevel(state.selectedLevel+1),550)};
}
async function openPersistent(n){state.selectedLevel=n;els.stage.innerHTML='<div class="miniGame"><div class="question">Loading your civilisation…</div></div>';try{await loadBuild();renderBuilder()}catch(err){console.error(err);els.stage.innerHTML='<div class="miniGame"><p class="question">Could not load your saved world.</p><p class="note">Please check the connection and try again.</p></div>'}}
startLevel=function(n){if(state.selected?.name==='Time Builder'){openPersistent(n);return}priorStart(n)};window.addEventListener('jamkar:auth',()=>{childId=null});window.addEventListener('jamkar:family',()=>{childId=null});
})();