(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let gl,canvas,program,raf=0,rot=0,active=true;
const vs=`attribute vec3 p;attribute vec3 c;uniform mat4 m;varying vec3 v;void main(){gl_Position=m*vec4(p,1.0);v=c;}`;
const fs=`precision mediump float;varying vec3 v;void main(){gl_FragColor=vec4(v,1.0);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s}
function init(){canvas=document.createElement('canvas');canvas.className='jamkar3d';canvas.setAttribute('aria-hidden','true');const hero=document.querySelector('.planetArt');if(!hero)return;hero.innerHTML='';hero.appendChild(canvas);gl=canvas.getContext('webgl',{alpha:true,antialias:true});if(!gl){hero.innerHTML='<div class="planet">🌍</div>';return}const v=shader(gl.VERTEX_SHADER,vs),f=shader(gl.FRAGMENT_SHADER,fs);program=gl.createProgram();gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);gl.useProgram(program);const P=[-1,-1,-1,1,-1,-1,1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,1,1,1,-1,1,1],C=[.2,.8,1,.4,.9,.7,.9,.7,.2,.8,.3,.8,.3,.6,1,.2,.9,.9,.9,.5,.3,.5,.4,1],I=[0,1,2,0,2,3,4,6,5,4,7,6,0,4,5,0,5,1,1,5,6,1,6,2,2,6,7,2,7,3,3,7,4,3,4,0];const pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(P),gl.STATIC_DRAW);const pa=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(pa);gl.vertexAttribPointer(pa,3,gl.FLOAT,false,0,0);const cb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(C),gl.STATIC_DRAW);const ca=gl.getAttribLocation(program,'c');gl.enableVertexAttribArray(ca);gl.vertexAttribPointer(ca,3,gl.FLOAT,false,0,0);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(I),gl.STATIC_DRAW);resize();addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(active)draw()});draw()}
function resize(){if(!canvas||!gl)return;const d=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth||320,h=canvas.clientHeight||320;canvas.width=w*d;canvas.height=h*d;gl.viewport(0,0,canvas.width,canvas.height)}
function mat(a){const c=Math.cos(a),s=Math.sin(a),c2=Math.cos(a*.7),s2=Math.sin(a*.7),z=-4,asp=(canvas.height||1)/(canvas.width||1);return new Float32Array([c*c2,s2,-s*c2,0,-c*s2,c2,s*s2,0,s,0,c,0,0,0,z,1].map((v,i)=>i===0||i===4?v*asp:v))}
function draw(){if(!active||!gl)return;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);rot+=reduced?0:.008;gl.uniformMatrix4fv(gl.getUniformLocation(program,'m'),false,mat(rot));gl.drawElements(gl.TRIANGLES,36,gl.UNSIGNED_SHORT,0);if(!reduced)raf=requestAnimationFrame(draw)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();