import { chromium, webkit } from 'playwright';
const browserName=(process.env.BROWSER||'chromium').toLowerCase();const browserType=browserName==='webkit'?webkit:chromium;const browser=await browserType.launch({headless:true});const activate=async locator=>locator.evaluate(el=>el.click());
async function desktopSmoke(){
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(()=>localStorage.setItem('jamkar_paid','yes'));await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await page.waitForSelector('#worlds .worldCard',{timeout:15000});
 if(!(await page.title()).includes('JamKar Online'))throw new Error('Unexpected page title');if(await page.locator('#worlds .worldCard').count()!==24)throw new Error('Expected 24 world cards');if(await page.evaluate(()=>localStorage.getItem('jamkar_paid')!==null))throw new Error('Legacy browser paid flag was not removed');if(!(await page.locator('.musicToggle').isVisible()))throw new Error('Music control is not visible');
 await activate(page.locator('.top .nav button').first());await page.waitForTimeout(120);if(await page.locator('.hero').isVisible())throw new Error('Games navigation did not switch to library view');await activate(page.locator('#worlds .worldCard').first());await page.waitForSelector('#worldModal.open');if(await page.locator('#levelGrid .level').count()!==30)throw new Error('Expected 30 levels');if(!(await page.locator('#levelGrid .level').nth(3).isDisabled()))throw new Error('Free user can access Level 4');await page.waitForSelector('.jkGameWorld',{timeout:5000});
 if(!(await page.locator('.jkGameCanvas').isVisible()))throw new Error('Playable canvas world missing');if(!(await page.locator('.jkMovePad').isVisible()))throw new Error('Movement controls missing');if(!(await page.locator('.jkMissionToggle').isVisible()))throw new Error('Mission toggle missing');if(!(await page.locator('#backWorld').isVisible()))throw new Error('Back button missing');if(await page.locator('.game3dEnvironment,.game3dCanvas,.adventureViewport,.nav3dPanel,.worldAmbience,.difficultyStrip').count())throw new Error('Deprecated gameplay layers are still mounted');
 const full=await page.evaluate(()=>{const r=document.querySelector('#worldModal .modalCard').getBoundingClientRect();return Math.abs(r.width-innerWidth)<3&&Math.abs(r.height-innerHeight)<3});if(!full)throw new Error('World does not fill viewport');const horizontal=await page.evaluate(()=>getComputedStyle(document.querySelector('#levelGrid')).display==='flex');if(!horizontal)throw new Error('Level rail is not horizontal');await activate(page.locator('.jkMissionToggle'));if(!(await page.locator('.jkQuest').evaluate(el=>el.classList.contains('is-hidden'))))throw new Error('Mission drawer does not hide');await activate(page.locator('#backWorld'));await page.waitForTimeout(80);if(await page.locator('#worldModal.open').count())throw new Error('Back button did not leave world');
 await activate(page.locator('#worlds .worldCard').nth(5));await page.waitForSelector('#accountModal.open');if(await page.locator('#worldModal.open').count())throw new Error('Paid world opened without entitlement');if(await page.locator('#child3').count())throw new Error('Unexpected third child profile field');if(await page.locator('#parentPassword').getAttribute('minlength')!=='8')throw new Error('Password minimum is not 8');if(!(await page.locator('.parentSafetyBox').isVisible()))throw new Error('Parent safety copy missing');if(errors.length)throw new Error(`${browserName} desktop page errors: `+errors.join(' | '));await page.close();
}
async function mobileSmoke(){
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await page.waitForSelector('#worlds .worldCard',{timeout:15000});if(!(await page.locator('.mobileDock').isVisible()))throw new Error('Mobile navigation dock missing');const bodyWidth=await page.evaluate(()=>document.documentElement.scrollWidth),viewportWidth=await page.evaluate(()=>innerWidth);if(bodyWidth>viewportWidth+2)throw new Error(`Mobile page overflow ${bodyWidth}>${viewportWidth}`);await activate(page.locator('#worlds .worldCard').first());await page.waitForSelector('.jkGameWorld');if(!(await page.locator('.jkGameCanvas').isVisible()))throw new Error('Mobile canvas missing');if(!(await page.locator('.jkMovePad').isVisible()))throw new Error('Mobile movement pad missing');if(!(await page.locator('#backWorld').isVisible()))throw new Error('Mobile back button missing');const overflow=await page.evaluate(()=>document.querySelector('#worldModal .modalCard').scrollWidth>innerWidth+2);if(overflow)throw new Error('World overflows mobile viewport');await activate(page.locator('#backWorld'));await activate(page.locator('.mobileDock [data-dock="parent"]'));await page.waitForSelector('#accountModal.open');if(errors.length)throw new Error(`${browserName} mobile page errors: `+errors.join(' | '));await page.close();
}
await desktopSmoke();await mobileSmoke();await browser.close();console.log(`${browserName} consolidated JamKar runtime passed.`);
