import { chromium } from 'playwright';

const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];
page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});
await page.waitForSelector('#worlds .worldCard',{timeout:15000});
const title=await page.title();
if(!title.includes('JamKar Online'))throw new Error('Unexpected page title');
const cards=await page.locator('#worlds .worldCard').count();
if(cards!==24)throw new Error(`Expected 24 world cards, found ${cards}`);
await page.locator('#worlds .worldCard').first().click();
await page.waitForSelector('#worldModal.open');
const levels=await page.locator('#levelGrid .level').count();
if(levels!==30)throw new Error(`Expected 30 levels, found ${levels}`);
await page.locator('#levelGrid .level').first().click();
await page.waitForTimeout(350);
if(!(await page.locator('#gameStage').textContent())?.trim())throw new Error('Game stage did not render');
await page.locator('#closeWorld').click();
await page.locator('#joinHero').click();
await page.waitForSelector('#accountModal.open');
if(await page.locator('#child3').count())throw new Error('Unexpected third child profile field');
const passMin=await page.locator('#parentPassword').getAttribute('minlength');
if(passMin!=='8')throw new Error('Password minimum is not 8');
if(errors.length)throw new Error('Browser page errors: '+errors.join(' | '));
await browser.close();
console.log('Browser smoke passed: home, 24 worlds, 30 levels, gameplay, parent account.');
