import fs from 'node:fs';

const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const app=read('app.js');
const index=read('index.html');
const free=read('free-games.js');
const extras=read('enhancements.js');
const completion=read('completion-api.js');
const expanded=read('expanded-games.js');
const builder=read('persistent-builder.js');
const recovery=read('auth-recovery.js');
const backend=read('backend.js');
const cloud=read('cloud-sync.js');
const account=read('account.js');
const polish=read('ui-polish.js');
const home=read('home-experience.js');
const admin=read('admin.js');
const adminHtml=read('admin.html');
const sunny=read('sunny-theme.css');
const more=read('more-worlds.js');
const progression=read('progression.js');
const navigation=read('world-navigation.js');
const environments=read('webgl-environments.js');
const characters=read('webgl-characters.js');

const checks=[];
const ok=(name,cond)=>checks.push({name,cond:!!cond});
const baseWorldNames=[...app.matchAll(/\{name:'([^']+)'/g)].map(m=>m[1]);
const extraWorldNames=[...more.matchAll(/name:'([^']+)'/g)].map(m=>m[1]);
const allWorldNames=[...baseWorldNames,...extraWorldNames];
const freeWorlds=[...app.matchAll(/\{name:'([^']+)'[^\n]*free:true/g)].map(m=>m[1]);
ok('24 game worlds declared',allWorldNames.length===24);
ok('World names unique',new Set(allWorldNames).size===24);
ok('Exactly 5 free worlds',freeWorlds.length===5);
ok('Level grid contains 30 levels',/Array\.from\(\{length:30\}/.test(app));
ok('Free trial locks after Level 3',/!state\.paid&&n>3/.test(app));
ok('Paid-only worlds route to unlock',/!state\.paid&&!w\.free/.test(app)&&/openAccount\('unlock'\)/.test(app));
ok('App starts unpaid and contains no local paid entitlement',/const state=\{paid:false/.test(app)&&!app.includes("localStorage.getItem('jamkar_paid')")&&!app.includes("localStorage.setItem('jamkar_paid'"));
ok('Browser paid flag removed in production sync',/removeItem\('jamkar_paid'\)/.test(cloud));
ok('Lifetime entitlement comes from Supabase family account',/lifetime_unlocked/.test(cloud));
ok('Revolut checkout invoked through backend',/backend\.createCheckout\(\)/.test(cloud));
ok('Parent password minimum is 8',/minlength="8"/.test(account)&&/pass\.length<8/.test(account));
ok('Parent sign out implemented',/parentSignOut/.test(account)&&/backend\.signOut\(\)/.test(account));
ok('Parent active child state syncs after family load and signout',/state\.activeProfile=names\[0\]/.test(account)&&/state\.activeProfile='Explorer'/.test(account));
ok('Persistent child profile state enabled locally and in cloud',/jamkar_profile/.test(home)&&/keepChildSession/.test(home)&&/last_active_slot/.test(backend)&&/setActiveChildSlot/.test(cloud));
ok('Password recovery implemented',/resetPasswordForEmail/.test(backend)&&/PASSWORD_RECOVERY/.test(recovery)&&/updatePassword/.test(backend));
ok('Password recovery hides while signed in',/forgot\.hidden=!!backend\.state\?\.user/.test(recovery));
ok('Two child profile fields only',index.includes('Child profile 1')&&index.includes('Child profile 2')&&!index.includes('Child profile 3'));
ok('Safety copy moved off the main page into Parent Area',!index.includes('No public chat')&&home.includes('No public chat')&&home.includes('moveSafetyToParent'));
ok('Privacy and terms links present',index.includes('legal.html#privacy')&&index.includes('legal.html#terms'));
ok('Five free mini-games implemented',['Dino Frontier','Deep Ocean','Ancient Worlds','Wild Planet','Deep Space'].every(n=>free.includes(`case'${n}'`)));
ok('Advanced mini-games implemented',['Memory Islands','Code Crew','Eco Rescue','Time Builder','Sky Racers'].every(n=>extras.includes(`case'${n}'`)));
ok('Remaining paid worlds have dynamic challenges',['Future City','Word Quest','Math Galaxy','Science Lab','Puzzle Temple','World Explorer'].every(n=>expanded.includes(`case'${n}'`)));
ok('Eight additional worlds have dedicated gameplay',['Music Makers','Art Studio','Weather Watch','Engineering Bay','Language Lab','Mystery Maze','Garden Guardians','Robot Factory'].every(n=>more.includes(n)));
ok('Persistent builder spans six eras',['prehistoric','settlement','ancient','industrial','modern','future'].every(e=>builder.includes(`key:'${e}'`)));
ok('Persistent builder syncs to backend',/loadWorldBuild/.test(builder)&&/saveWorldBuild/.test(builder)&&/world_builds/.test(backend));
ok('Persistent builder has civilisation needs',/civStats/.test(builder)&&/Era mission/.test(builder)&&/Robotics/.test(builder)&&/Solar/.test(builder));
ok('Persistent builder and recovery scripts loaded',index.includes('persistent-builder.js')&&index.includes('auth-recovery.js'));
ok('Shared completion API loaded before builder',index.indexOf('completion-api.js')>index.indexOf('enhancements.js')&&index.indexOf('completion-api.js')<index.indexOf('persistent-builder.js'));
ok('Shared completion handles milestones and world mastery',/JamKarCompleteLevel/.test(completion)&&/World Master/.test(completion)&&/Level 20 Pathfinder/.test(completion));
ok('Cloud achievements load and save',/loadAchievements/.test(cloud)&&/saveAchievement/.test(cloud)&&/jamkar:achievement/.test(cloud));
ok('3D mission events sync into child achievement storage',/jamkar:3dmission/.test(navigation)&&/mission3d\|/.test(cloud)&&/merge3DMissions/.test(cloud));
ok('Progression system loaded',index.includes('progression.js')&&index.includes('progression.css'));
ok('Progression has six mastery tiers',['Explorer','Adventurer','Pathfinder','Master','Champion','Legend'].every(x=>progression.includes(`name:'${x}'`)));
ok('Progression awards XP stars streaks badges',/prog\.xp\+=/.test(progression)&&/prog\.stars\+=/.test(progression)&&/prog\.streak=/.test(progression)&&/addBadge/.test(progression));
ok('Companion evolution implemented',['Spark Egg','Spark Cub','Quest Buddy','Star Hero','Legend Companion'].every(x=>progression.includes(x)));
ok('Expanded challenges loaded after free game layer',index.indexOf('expanded-games.js')>index.indexOf('free-games.js'));
ok('Child-first light theme loaded last',index.includes('sunny-theme.css')&&index.includes('home-experience.js')&&/cardFloat/.test(sunny));
ok('Music control implemented',/AudioContext/.test(home)&&/musicToggle/.test(home));
ok('All 24 worlds have dedicated palettes',allWorldNames.every(n=>home.includes(`'${n}':[`))&&home.includes('paletteFor')&&sunny.includes('data-world-theme="custom"')&&sunny.includes('--world-a')&&sunny.includes('--world-b'));
ok('Admin page and secure RPC controls wired',adminHtml.includes('JamKar Admin')&&/admin_get_overview/.test(admin)&&/admin_set_family_unlock/.test(admin));
ok('Mobile/kid navigation polish loaded',index.includes('ui-polish.js')&&index.includes('polish.css'));
ok('Create/My Worlds navigation wired',polish.includes('openBuilder')&&polish.includes('openMyWorlds'));
ok('Native WebGL world and characters loaded',index.includes('webgl-world.js')&&index.includes('webgl-characters.js')&&/getContext\('webgl'/.test(characters));
ok('Interactive 3D navigation loaded',index.includes('world-navigation.js')&&/JamKar3DPlayer/.test(navigation)&&/WASD/.test(navigation));
ok('3D landmark missions persist per child profile',/jamkar_3dmissions_/.test(navigation)&&/JamKar3DWorldState/.test(navigation));
ok('Completed missions visibly alter environments',/jamkar:worldstate/.test(environments)&&/done\(0\)/.test(environments)&&/done\(2\)/.test(environments));
ok('Reduced-motion accessibility supported',read('polish.css').includes('prefers-reduced-motion')&&read('progression.css').includes('prefers-reduced-motion'));
ok('Supabase client library pinned',/@supabase\/supabase-js@2\.112\.4/.test(index));

const failed=checks.filter(x=>!x.cond);
for(const c of checks)console.log(`${c.cond?'PASS':'FAIL'}  ${c.name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`);
if(failed.length)process.exit(1);
